//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sportsman.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://schoolsport.org.il:8080/ISF/SportServices/AdvancedService.asmx")]
        public string Sportsman_AdvancedServices_AdvancedService {
            get {
                return ((string)(this["Sportsman_AdvancedServices_AdvancedService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://schoolsport.org.il:8080/ISF/SportServices/ChampionshipService.asmx")]
        public string Sportsman_ChampionshipServices_ChampionshipService {
            get {
                return ((string)(this["Sportsman_ChampionshipServices_ChampionshipService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://schoolsport.org.il:8080/ISF/SportServices/PermissionService.asmx")]
        public string Sportsman_PermissionServices_PermissionService {
            get {
                return ((string)(this["Sportsman_PermissionServices_PermissionService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://schoolsport.org.il:8080/ISF/SportServices/SessionService.asmx")]
        public string Sportsman_SessionServices_SessionService {
            get {
                return ((string)(this["Sportsman_SessionServices_SessionService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://schoolsport.org.il:8080/ISF/SportServices/DataService.asmx")]
        public string Sport_Championships_DataServices_DataService {
            get {
                return ((string)(this["Sport_Championships_DataServices_DataService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://schoolsport.org.il:8080/ISF/SportServices/ChampionshipService.asmx")]
        public string Sport_Championships_SportServices_ChampionshipService {
            get {
                return ((string)(this["Sport_Championships_SportServices_ChampionshipService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://schoolsport.org.il:8080/ISF/SportServices/DataService.asmx")]
        public string Sportsman_DataServices_DataService {
            get {
                return ((string)(this["Sportsman_DataServices_DataService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://schoolsport.org.il:8080/ISF/SportServices/PlayerCardService.asmx")]
        public string Sportsman_PlayerCardServices_PlayerCardService {
            get {
                return ((string)(this["Sportsman_PlayerCardServices_PlayerCardService"]));
            }
        }
    }
}
