 ALTER TABLE BUGS ADD DATE_DELETED datetime
 ALTER TABLE CHAMPIONSHIPS ADD DATE_DELETED datetime
 ALTER TABLE CHAMPIONSHIP_CATEGORIES ADD DATE_DELETED datetime
 ALTER TABLE CHAMPIONSHIP_REGIONS ADD DATE_DELETED datetime
 ALTER TABLE CHARGES ADD DATE_DELETED datetime
 ALTER TABLE CITIES ADD DATE_DELETED datetime
 ALTER TABLE COURTS ADD DATE_DELETED datetime
 ALTER TABLE COURT_TYPES ADD DATE_DELETED datetime
 ALTER TABLE COURT_TYPE_SPORTS ADD DATE_DELETED datetime
 ALTER TABLE FACILITIES ADD DATE_DELETED datetime
 ALTER TABLE GAME_BOARDS ADD DATE_DELETED datetime
 ALTER TABLE MESSAGES ADD DATE_DELETED datetime
 ALTER TABLE PHASE_PATTERNS ADD DATE_DELETED datetime
 ALTER TABLE PLAYERS ADD DATE_DELETED datetime
 ALTER TABLE PRODUCTS ADD DATE_DELETED datetime
 ALTER TABLE REFEREES ADD DATE_DELETED datetime
 ALTER TABLE REGIONS ADD DATE_DELETED datetime
 ALTER TABLE RULESETS ADD DATE_DELETED datetime
 ALTER TABLE SCHOOLS ADD DATE_DELETED datetime
 ALTER TABLE SEASONS ADD DATE_DELETED datetime
 ALTER TABLE SPORTS ADD DATE_DELETED datetime
 ALTER TABLE SPORT_FIELDS ADD DATE_DELETED datetime
 ALTER TABLE SPORT_FIELD_TYPES ADD DATE_DELETED datetime
 ALTER TABLE STANDARD_CHAMPIONSHIPS ADD DATE_DELETED datetime
 ALTER TABLE STANDARD_CHAMPIONSHIP_CATEGORIES ADD DATE_DELETED datetime
 ALTER TABLE STUDENTS ADD DATE_DELETED datetime
 ALTER TABLE TEAMS ADD DATE_DELETED datetime
 ALTER TABLE USERS ADD DATE_DELETED datetime
 GO
 
-------------------------------
--UNIQUE constraints
-------------------------------

ALTER TABLE STANDARD_CHAMPIONSHIPS DROP CONSTRAINT UN_STDCHAMP_NAMEREG
GO

ALTER TABLE STANDARD_CHAMPIONSHIPS ADD
CONSTRAINT UN_STDCHAMP_NAMEREG UNIQUE(STANDARD_CHAMPIONSHIP_NAME, IS_REGIONAL, DATE_DELETED)
GO

ALTER TABLE CHAMPIONSHIPS DROP CONSTRAINT UN_CHAMPIONSHIPS_NAME
GO

ALTER TABLE CHAMPIONSHIPS ADD
CONSTRAINT UN_CHAMPIONSHIPS_NAME UNIQUE(SEASON, REGION_ID, CHAMPIONSHIP_NAME, DATE_DELETED)
GO

ALTER TABLE SCHOOLS ALTER COLUMN SYMBOL nchar(6) NOT NULL
GO

ALTER TABLE SCHOOLS DROP CONSTRAINT UN_SCHOOL_SYMBOL
GO

ALTER TABLE SCHOOLS ADD
CONSTRAINT UN_SCHOOL_SYMBOL UNIQUE(SYMBOL, DATE_DELETED)
GO

ALTER TABLE STUDENTS ALTER COLUMN ID_NUMBER int NOT NULL
GO

ALTER TABLE STUDENTS DROP CONSTRAINT UN_STUDENT_ID_NUMBER
GO

ALTER TABLE STUDENTS ADD
CONSTRAINT UN_STUDENT_ID_NUMBER UNIQUE(ID_NUMBER, DATE_DELETED)
GO

ALTER TABLE GAME_BOARDS ALTER COLUMN GAME_BOARD_NAME nvarchar(50) NOT NULL
GO

ALTER TABLE GAME_BOARDS DROP CONSTRAINT UN_GAME_BOARD_NAME
GO

ALTER TABLE GAME_BOARDS ADD
CONSTRAINT UN_GAME_BOARD_NAME UNIQUE(GAME_BOARD_NAME, DATE_DELETED)
GO

ALTER TABLE PHASE_PATTERNS ALTER COLUMN PHASE_PATTERN_NAME nvarchar(50) NOT NULL
GO

ALTER TABLE PHASE_PATTERNS DROP CONSTRAINT UN_PHASE_PATTERN_NAME
GO

ALTER TABLE PHASE_PATTERNS ADD
CONSTRAINT UN_PHASE_PATTERN_NAME UNIQUE(PHASE_PATTERN_NAME, DATE_DELETED)
GO

ALTER TABLE RULESETS ALTER COLUMN RULESET_NAME nvarchar(30) NOT NULL
GO

ALTER TABLE RULESETS DROP CONSTRAINT UN_RULESET_NAME
GO

ALTER TABLE RULESETS ADD
CONSTRAINT UN_RULESET_NAME UNIQUE(RULESET_NAME, DATE_DELETED)
GO

ALTER TABLE PRODUCTS DROP CONSTRAINT UN_PRODUCT_NAME
GO

ALTER TABLE PRODUCTS ADD
CONSTRAINT UN_PRODUCT_NAME UNIQUE(PRODUCT_NAME, DATE_DELETED)
GO

ALTER TABLE PLAYERS DROP CONSTRAINT UN_PLAYER_TEAM_STUDENT
GO

ALTER TABLE PLAYERS ADD
CONSTRAINT UN_PLAYER_TEAM_STUDENT UNIQUE(TEAM_ID, STUDENT_ID, DATE_DELETED)
GO

ALTER TABLE SPORT_FIELDS DROP CONSTRAINT UN_SPORTFIELD_TYPEFIELD
GO

ALTER TABLE SPORT_FIELDS ADD
CONSTRAINT UN_SPORTFIELD_TYPEFIELD UNIQUE(SPORT_FIELD_TYPE_ID, SPORT_FIELD_ID, DATE_DELETED)
GO

ALTER TABLE USERS ALTER COLUMN USER_LOGIN nvarchar(20) NOT NULL
GO

ALTER TABLE USERS DROP CONSTRAINT UN_USER_LOGIN
GO

ALTER TABLE USERS ADD
CONSTRAINT UN_USER_LOGIN UNIQUE(USER_LOGIN, DATE_DELETED)
GO

---ALTER TABLE STUDENT_CARDS DROP CONSTRAINT UN_CARD_STUDENT_SPORT
---GO

---ALTER TABLE STUDENT_CARDS ADD
---CONSTRAINT UN_CARD_STUDENT_SPORT UNIQUE(STUDENT_ID,SPORT_ID,DATE_DELETED)
---GO

---ALTER TABLE CHAMPIONSHIP_PHASES DROP CONSTRAINT UN_CHAMPPHASE_NAME
---GO

---ALTER TABLE CHAMPIONSHIP_PHASES ADD
---CONSTRAINT UN_CHAMPPHASE_NAME UNIQUE(CHAMPIONSHIP_CATEGORY_ID, PHASE_NAME, DATE_DELETED)
---GO

---ALTER TABLE CHAMPIONSHIP_GROUPS DROP CONSTRAINT UN_CHAMPGROUP_NAME
---GO

---ALTER TABLE CHAMPIONSHIP_GROUPS ADD
---CONSTRAINT UN_CHAMPGROUP_NAME UNIQUE(CHAMPIONSHIP_CATEGORY_ID, PHASE, GROUP_NAME, DATE_DELETED)
---GO

---ALTER TABLE CHAMPIONSHIP_ROUNDS DROP CONSTRAINT UN_CHAMPROUND_NAME
---GO

---ALTER TABLE CHAMPIONSHIP_ROUNDS ADD
---CONSTRAINT UN_CHAMPROUND_NAME UNIQUE(CHAMPIONSHIP_CATEGORY_ID, PHASE, NGROUP, ROUND_NAME, DATE_DELETED)
---GO