ALTER TABLE CHAMPIONSHIP_MATCHES
ALTER COLUMN TEAM_A_SCORE real
GO

ALTER TABLE CHAMPIONSHIP_MATCHES
ALTER COLUMN TEAM_B_SCORE real
GO

ALTER TABLE CHAMPIONSHIP_GROUP_TEAMS
DROP CONSTRAINT CHK_CHAMPGROUP_SCORE
GO

ALTER TABLE CHAMPIONSHIP_GROUP_TEAMS
ALTER COLUMN SCORE real
GO

ALTER TABLE CHAMPIONSHIP_GROUP_TEAMS
ADD CONSTRAINT
CHK_CHAMPGROUP_SCORE CHECK (
(TEAM_ID IS NOT NULL) OR (GAMES IS NULL AND SCORE IS NULL))
GO

UPDATE RULES SET VALUE=REPLACE(CONVERT(nvarchar(1000), VALUE), '.', '|')
WHERE RULE_TYPE_ID=1 OR RULE_TYPE_ID=2
GO