CREATE TABLE CHAMPIONSHIP_PHASE_DEFINITIONS (
CHAMPIONSHIP_CATEGORY_ID	int				NOT NULL,
PHASE						int				NOT NULL,
RULE_TYPE_ID				int				NOT NULL,
DEFINITION					nvarchar(100)	NOT NULL,
VALUE						nvarchar(100)	NOT NULL,
DATE_LAST_MODIFIED DATETIME,
DATE_DELETED datetime,
timestamp,
CONSTRAINT PK_CHAMPIONSHIP_PHASE_DEFINITIONS PRIMARY KEY(CHAMPIONSHIP_CATEGORY_ID, PHASE, RULE_TYPE_ID, DEFINITION),
CONSTRAINT FK_CHAMPPHASEDEF_PHASE FOREIGN KEY(CHAMPIONSHIP_CATEGORY_ID, PHASE)
	REFERENCES CHAMPIONSHIP_PHASES(CHAMPIONSHIP_CATEGORY_ID, PHASE),
CONSTRAINT FK_CHAMPPHASEDEF_RULETYPE FOREIGN KEY(RULE_TYPE_ID)
	REFERENCES RULE_TYPES(RULE_TYPE_ID)
)
GO

INSERT INTO RULE_TYPES (RULE_TYPE_ID, CLASS)
VALUES (16, 'Sport.Rulesets.Rules.TeamPhaseScoringRule,Sport.Rulesets')
GO

UPDATE RULE_TYPES
SET CLASS = 'Sport.Rulesets.Rules.RankingTablesRule,Sport.Rulesets'
WHERE RULE_TYPE_ID = 3
GO