ALTER TABLE WEBSITE_POLLS ADD
CREATOR int
GO

ALTER TABLE WEBSITE_POLLS ADD
CONSTRAINT FK_POLL_CREATOR FOREIGN KEY(CREATOR) 
REFERENCES USERS(USER_ID)
GO 

ALTER TABLE WEBSITE_POLLS ADD
ARCHIVE_DATE datetime
GO

ALTER TABLE WEBSITE_POLLS_POSSIBLE_ANSWERS ADD
ARCHIVE_DATE datetime
GO

ALTER TABLE ISF_FLASH_NEWS ADD
FLASH_NEWS_LINKS nvarchar(1024)
GO

ALTER TABLE ISF_ARTICLES ADD
AUTHOR_NAME nvarchar(50)
GO

ALTER TABLE WEBSITE_ARTICLE_COMMENTS ADD
SUBMISSION_TIME datetime NOT NULL DEFAULT GETDATE()
GO

ALTER TABLE WEBSITE_IMAGE_GALLERY ADD
SUB_GROUP nvarchar(100)
GO

UPDATE WEBSITE_IMAGE_GALLERY SET SUB_GROUP=GROUP_NAME
GO

ALTER TABLE WEBSITE_PAGES ADD
PAGE_LINKS nvarchar(1024)
GO

ALTER TABLE ISF_ARTICLES ADD
DATE_LAST_MODIFIED DATETIME
GO

ALTER TABLE WEBSITE_VISITORS
DROP CONSTRAINT UN_VISITOR_IP
GO

ALTER TABLE WEBSITE_VISITORS
ADD CONSTRAINT UN_VISITOR_IP_AGENT UNIQUE(IP_ADDRESS, USER_AGENT)
GO

ALTER TABLE PENDING_COMPETITORS ADD
CONSTRAINT UN_PENDING_COMPETITOR_PLAYER UNIQUE(PLAYER_ID, COMPETITION_INDEX)
GO

ALTER TABLE PENDING_COMPETITORS ADD
PHASE_NAME nvarchar(50)
GO

ALTER TABLE PENDING_COMPETITORS ADD
GROUP_NAME nvarchar(50)
GO

ALTER TABLE PENDING_MATCH_SCORES ADD
CONSTRAINT UN_PENDING_MATCH_MATCH UNIQUE(CHAMPIONSHIP_CATEGORY_ID, PHASE, NGROUP, ROUND, CYCLE, MATCH)
GO

ALTER TABLE PENDING_MATCH_SCORES ADD
SENDER int
GO

ALTER TABLE PENDING_MATCH_SCORES ADD
CONSTRAINT FK_PENDING_MATCH_SENDER FOREIGN KEY(SENDER) REFERENCES USERS(USER_ID)
GO

ALTER TABLE PENDING_MATCH_SCORES ADD
PARTS_RESULT nvarchar(2000)
GO