-Update PLAYERS Set GOT_STICKER=1
Where PLAYER_ID In (Select Distinct p.PLAYER_ID
From STUDENT_CARDS sc Inner Join CHAMPIONSHIPS c On sc.SPORT_ID=c.SPORT_ID
Inner Join CHAMPIONSHIP_CATEGORIES cc On cc.CHAMPIONSHIP_ID=c.CHAMPIONSHIP_ID
Inner Join TEAMS t On t.CHAMPIONSHIP_CATEGORY_ID=cc.CHAMPIONSHIP_CATEGORY_ID
Inner Join PLAYERS p On p.TEAM_ID=t.TEAM_ID And sc.STUDENT_ID=p.STUDENT_ID
Where sc.ISSUE_DATE Is Not Null)
GO