-- =======    SPORTS TABLE   ======
CREATE TABLE SPORTS (
SPORT_ID	int				IDENTITY (1,1),
SPORT_NAME	nvarchar(50),
SPORT_TYPE	int				NOT NULL, -- 1 Competition 2 Match
POINTS_NAME			nvarchar(20),
DATE_LAST_MODIFIED DATETIME,
DATE_DELETED datetime,
timestamp
CONSTRAINT PK_SPORTS PRIMARY KEY(SPORT_ID),
CONSTRAINT CHK_SPORT_TYPE CHECK (SPORT_TYPE IN (1, 2))
)
GO

-- =======    SPORT_FIELD_TYPES TABLE   ======
CREATE TABLE SPORT_FIELD_TYPES (
SPORT_FIELD_TYPE_ID		int		IDENTITY (1,1),
SPORT_ID				int,
SPORT_FIELD_TYPE_NAME	nvarchar(50),
DATE_LAST_MODIFIED DATETIME,
DATE_DELETED datetime,
timestamp,
CONSTRAINT PK_SPORT_FIELD_TYPES PRIMARY KEY(SPORT_FIELD_TYPE_ID),
CONSTRAINT FK_SPORTFIELDTYPE_SPORT FOREIGN KEY(SPORT_ID)
	REFERENCES SPORTS(SPORT_ID)
)
GO

-- =======    SPORT_FIELDS TABLE   ======
CREATE TABLE SPORT_FIELDS (
SPORT_FIELD_ID		int		IDENTITY (1,1),
SPORT_FIELD_TYPE_ID int,
SPORT_FIELD_NAME	nvarchar(50),
DATE_LAST_MODIFIED DATETIME,
DATE_DELETED datetime,
timestamp,
CONSTRAINT PK_SPORT_FIELDS PRIMARY KEY(SPORT_FIELD_ID),
CONSTRAINT FK_SPORTFIELD_FIELDTYPE FOREIGN KEY(SPORT_FIELD_TYPE_ID)
	REFERENCES SPORT_FIELD_TYPES(SPORT_FIELD_TYPE_ID),
CONSTRAINT UN_SPORTFIELD_TYPEFIELD UNIQUE(SPORT_FIELD_TYPE_ID, SPORT_FIELD_ID, DATE_DELETED)
)
GO

-- =======    FACILITIES TABLE   ======
CREATE TABLE FACILITIES (
FACILITY_ID		int				IDENTITY (1,1),
FACILITY_NAME	nvarchar(30)	NOT NULL,
REGION_ID		int,
SCHOOL_ID		int,
ADDRESS			nvarchar(70),
PHONE			nvarchar(15),
FAX				nvarchar(15),
CITY_ID			int,
DATE_LAST_MODIFIED DATETIME,
DATE_DELETED datetime,
timestamp,
CONSTRAINT PK_FACILITY PRIMARY KEY(FACILITY_ID),
CONSTRAINT FK_FACILITIES_SCHOOL FOREIGN KEY(SCHOOL_ID)
	REFERENCES SCHOOLS(SCHOOL_ID),
CONSTRAINT FK_FACILITIES_REGION FOREIGN KEY(REGION_ID)
	REFERENCES REGIONS(REGION_ID)
CONSTRAINT FK_FACILITIES_CITY FOREIGN KEY(CITY_ID)
	REFERENCES CITIES(CITY_ID)
)
GO

-- =======    COURT_TYPES TABLE   ======
CREATE TABLE COURT_TYPES (
COURT_TYPE_ID		int				IDENTITY (1,1),
COURT_TYPE_NAME		nvarchar(30)	NOT NULL,
DATE_LAST_MODIFIED DATETIME,
DATE_DELETED datetime,
timestamp,
CONSTRAINT PK_COURT_TYPES PRIMARY KEY(COURT_TYPE_ID)
)
GO

-- =======    COURT_TYPE_SPORTS TABLE   ======
CREATE TABLE COURT_TYPE_SPORTS (
COURT_TYPE_SPORT_ID		int				IDENTITY (1,1),
COURT_TYPE_ID			int NOT NULL,
SPORT_ID				int NOT NULL,
SPORT_FIELD_TYPE_ID		int,
SPORT_FIELD_ID			int,
DATE_LAST_MODIFIED DATETIME,
DATE_DELETED datetime,
timestamp,
CONSTRAINT PK_COURT_TYPE_SPORTS PRIMARY KEY(COURT_TYPE_SPORT_ID),
CONSTRAINT FK_COURTTYPESPORT_TYPE FOREIGN KEY(COURT_TYPE_ID)
	REFERENCES COURT_TYPES(COURT_TYPE_ID),
CONSTRAINT FK_COURTTYPESPORT_SPORT FOREIGN KEY(SPORT_ID)
	REFERENCES SPORTS(SPORT_ID),
CONSTRAINT FK_COURTTYPESPORT_FIELDTYPE FOREIGN KEY(SPORT_FIELD_TYPE_ID)
	REFERENCES SPORT_FIELD_TYPES(SPORT_FIELD_TYPE_ID),
CONSTRAINT FK_COURTTYPESPORT_FIELD FOREIGN KEY(SPORT_FIELD_ID)
	REFERENCES SPORT_FIELDS(SPORT_FIELD_ID)
)
GO

-- =======    COURTS TABLE   ======
CREATE TABLE COURTS (
COURT_ID		int				IDENTITY (1,1),
COURT_NAME		nvarchar(30)	NOT NULL,
FACILITY_ID		int NOT NULL,
COURT_TYPE_ID	int,
DATE_LAST_MODIFIED DATETIME,
DATE_DELETED datetime,
timestamp,
CONSTRAINT PK_COURT PRIMARY KEY(COURT_ID),
CONSTRAINT FK_COURT_FACILITY FOREIGN KEY(FACILITY_ID)
	REFERENCES FACILITIES(FACILITY_ID),
CONSTRAINT FK_COURT_TYPE FOREIGN KEY(COURT_TYPE_ID)
	REFERENCES COURT_TYPES(COURT_TYPE_ID)
)
GO

-- =======    REFEREES TABLE   ======
CREATE TABLE REFEREES (
REFEREE_ID		int				IDENTITY (1,1),
REFEREE_NAME	nvarchar(50)	NOT NULL,
REFEREE_TYPE	int				NOT NULL,	--Minor/Senior
DATE_LAST_MODIFIED DATETIME,
DATE_DELETED datetime,
timestamp,
CONSTRAINT PK_REFEREE PRIMARY KEY(REFEREE_ID)
)
GO

-- =======    BUGS TABLE   ======
CREATE TABLE BUGS (
BUG_ID			int				IDENTITY (1,1),
BUG_DATE		datetime		NOT NULL,
TITLE			nvarchar(50)	NOT NULL,
DESCRIPTION		nvarchar(1024),
STATUS			int				NOT NULL,
USER_ID			int,
TYPE			int,
DATE_LAST_MODIFIED DATETIME,
DATE_DELETED datetime,
timestamp,
CONSTRAINT PK_BUGS PRIMARY KEY(BUG_ID),
CONSTRAINT FK_BUGS_USER FOREIGN KEY(USER_ID) REFERENCES USERS(USER_ID))
GO

-- =======    CHARGES TABLE   ======
CREATE TABLE CHARGES (
CHARGE_ID		int			IDENTITY(1, 1),
SCHOOL_ID		int			NOT NULL,
PRODUCT_ID		int			NOT NULL,
CHARGE_PRICE	float		NOT NULL DEFAULT 0,
CHARGE_DATE		datetime	NOT NULL DEFAULT GETDATE(),
STATUS			int,
CHAMPIONSHIP	int,
DATE_LAST_MODIFIED DATETIME,
DATE_DELETED datetime,
timestamp,
CONSTRAINT PK_CHARGES PRIMARY KEY(CHARGE_ID),
CONSTRAINT FK_CHARGE_SCHOOL FOREIGN KEY(SCHOOL_ID)
	REFERENCES SCHOOLS(SCHOOL_ID),
CONSTRAINT FK_CHARGE_PRODUCT FOREIGN KEY(PRODUCT_ID)
	REFERENCES PRODUCTS(PRODUCT_ID)
)
GO

-- =======    PAYMENTS TABLE   ======
CREATE TABLE PAYMENTS (
PAYMENT_ID		int			IDENTITY(1, 1),
SCHOOL_ID		int			NOT NULL,
CHARGE_ID		int,
PAYMENT_SUM		float		NOT NULL DEFAULT 0,
PAYMENT_DATE	datetime	NOT NULL DEFAULT GETDATE(),
PAYMENT_TYPE	int,
DESCRIPTION		nvarchar(255),
PAID_BY			nvarchar(100),
CREDIT_CARD_TYPE int,
CREDIT_CARD_LAST_DIGITS int,
CREDIT_CARD_EXPIRE_DATE datetime,
CREDIT_CARD_PAYMENTS int, 
DATE_LAST_MODIFIED DATETIME,
DATE_DELETED datetime,
timestamp,
CONSTRAINT PK_PAYMENTS PRIMARY KEY(PAYMENT_ID),
CONSTRAINT FK_PAYMENT_SCHOOL FOREIGN KEY(SCHOOL_ID)
	REFERENCES SCHOOLS(SCHOOL_ID),
CONSTRAINT FK_PAYMENT_CHARGE FOREIGN KEY(CHARGE_ID)
	REFERENCES CHARGES(CHARGE_ID)
)
GO

-- =======    MESSAGES TABLE   ======
CREATE TABLE  MESSAGES (
MESSAGE_ID		int	IDENTITY(1, 1), 
USER_ID			int	NOT NULL,
MESSAGE_TYPE	int, 
MESSAGE_STATUS	int	NOT NULL, 
MESSAGE_TEXT	nvarchar(255) NOT NULL, 
TIME_SENT		datetime	NOT NULL,
TIME_READ		datetime,
DATE_LAST_MODIFIED DATETIME,
DATE_DELETED datetime,
timestamp,
CONSTRAINT PK_MESSAGES PRIMARY KEY(MESSAGE_ID),
CONSTRAINT FK_MESSAGES_USER FOREIGN KEY(USER_ID)
	REFERENCES USERS(USER_ID))
GO

-- =======    GAME_BOARDS   ======
CREATE TABLE GAME_BOARDS (
GAME_BOARD_ID	int				IDENTITY (1,1),
GAME_BOARD_NAME	nvarchar(50)	NOT NULL,
RANGE			nvarchar(100),
DATA			ntext,
DATE_LAST_MODIFIED DATETIME,
DATE_DELETED datetime,
timestamp,
CONSTRAINT PK_GAME_BOARDS PRIMARY KEY(GAME_BOARD_ID),
CONSTRAINT UN_GAME_BOARD_NAME UNIQUE(GAME_BOARD_NAME, DATE_DELETED)
)
GO

-- =======    PHASE_PATTERNS   ======
CREATE TABLE PHASE_PATTERNS (
PHASE_PATTERN_ID	int				IDENTITY (1,1),
PHASE_PATTERN_NAME	nvarchar(50)	NOT NULL,
RANGE				nvarchar(100),
DATA				ntext,
DATE_LAST_MODIFIED DATETIME,
DATE_DELETED datetime,
timestamp,
CONSTRAINT PK_PHASE_PATTERNS PRIMARY KEY(PHASE_PATTERN_ID),
CONSTRAINT UN_PHASE_PATTERN_NAME UNIQUE(PHASE_PATTERN_NAME, DATE_DELETED)
)
GO

-- =======    RULESETS TABLE   ======
CREATE TABLE RULESETS (
RULESET_ID		int				IDENTITY (1,1),
RULESET_NAME	nvarchar(30)	NOT NULL,
SPORT_ID		int,
REGION_ID		int,
DATE_LAST_MODIFIED DATETIME,
DATE_DELETED datetime,
timestamp,
CONSTRAINT PK_RULESETS PRIMARY KEY(RULESET_ID),
CONSTRAINT UN_RULESET_NAME UNIQUE(RULESET_NAME, DATE_DELETED),
CONSTRAINT FK_RULESET_SPORT FOREIGN KEY(SPORT_ID)
	REFERENCES SPORTS(SPORT_ID),
CONSTRAINT FK_RULESET_REGION FOREIGN KEY(REGION_ID)
	REFERENCES REGIONS(REGION_ID),
)
GO

-- Adding columns to SPORTS table
ALTER TABLE SPORTS
ADD RULESET_ID		int,
CONSTRAINT FK_SPORT_RULESET FOREIGN KEY(RULESET_ID)
	REFERENCES RULESETS(RULESET_ID)
GO

-- =======    RULES TABLE   ======
CREATE TABLE RULES (
RULE_ID					int		IDENTITY (1,1),
RULESET_ID				int		NOT NULL,
RULE_TYPE_ID			int		NOT NULL,
VALUE					ntext,
SPORT_FIELD_TYPE_ID		int,
SPORT_FIELD_ID			int,
CATEGORY				int,
DATE_LAST_MODIFIED DATETIME,
DATE_DELETED datetime,
timestamp,
CONSTRAINT PK_RULES PRIMARY KEY(RULE_ID),
CONSTRAINT FK_RULE_RULESET FOREIGN KEY(RULESET_ID)
	REFERENCES RULESETS(RULESET_ID),
CONSTRAINT FK_RULE_RULETYPE FOREIGN KEY(RULE_TYPE_ID)
	REFERENCES RULE_TYPES(RULE_TYPE_ID),
CONSTRAINT FK_RULE_SPORTFIELDTYPE FOREIGN KEY(SPORT_FIELD_TYPE_ID)
	REFERENCES SPORT_FIELD_TYPES(SPORT_FIELD_TYPE_ID),
CONSTRAINT FK_RULE_SPORTFIELD FOREIGN KEY(SPORT_FIELD_ID)
	REFERENCES SPORT_FIELDS(SPORT_FIELD_ID)
)
GO

-- =======    STANDARD_CHAMPIONSHIPS TABLE   ======
CREATE TABLE STANDARD_CHAMPIONSHIPS (
STANDARD_CHAMPIONSHIP_ID	int				IDENTITY (1,1),
STANDARD_CHAMPIONSHIP_NAME	nvarchar(50),
SPORT_ID					int NOT NULL,
IS_REGIONAL					int NOT NULL, -- 0 no, 1 yes
IS_OPEN						int NOT NULL, -- 0 no, 1 yes for central championships only.
IS_CLUBS					int NOT NULL,
RULESET_ID					int,
DATE_LAST_MODIFIED DATETIME,
DATE_DELETED datetime,
timestamp,
CONSTRAINT PK_STANDARD_CHAMPIONSHIPS PRIMARY KEY(STANDARD_CHAMPIONSHIP_ID),
CONSTRAINT UN_STDCHAMP_NAMEREG UNIQUE(STANDARD_CHAMPIONSHIP_NAME, IS_REGIONAL, DATE_DELETED),
CONSTRAINT FK_STDCHAMP_SPORT FOREIGN KEY(SPORT_ID)
	REFERENCES SPORTS(SPORT_ID),
CONSTRAINT FK_STDCHAMP_RULESET FOREIGN KEY(RULESET_ID)
	REFERENCES RULESETS(RULESET_ID),
CONSTRAINT CHK_STDCHAMP_REGIONAL CHECK (IS_REGIONAL = 0 OR IS_REGIONAL = 1),
CONSTRAINT CHK_STDCHAMP_OPEN CHECK (IS_OPEN = 0 OR IS_OPEN = 1),
CONSTRAINT CHK_STDCHAMP_CLUBS CHECK (IS_CLUBS = 0 OR IS_CLUBS = 1)
)
GO

-- =======    STANDARD_CHAMPIONSHIP_CATEGORIES TABLE   ======
CREATE TABLE STANDARD_CHAMPIONSHIP_CATEGORIES (
STANDARD_CHAMPIONSHIP_CATEGORY_ID	int		IDENTITY (1,1),
STANDARD_CHAMPIONSHIP_ID			int		NOT NULL,
CATEGORY							int		NOT NULL,
DATE_LAST_MODIFIED DATETIME,
DATE_DELETED datetime,
timestamp,
CONSTRAINT PK_STANDARD_CHAMPIONSHIP_CATEGORIES PRIMARY KEY(STANDARD_CHAMPIONSHIP_CATEGORY_ID),
CONSTRAINT FK_STANDARD_CHAMPIONCAT_CHAMPIONSHIP FOREIGN KEY(STANDARD_CHAMPIONSHIP_ID)
	REFERENCES STANDARD_CHAMPIONSHIPS(STANDARD_CHAMPIONSHIP_ID)
)
GO

-- =======    CHAMPIONSHIPS TABLE   ======
CREATE TABLE CHAMPIONSHIPS (
CHAMPIONSHIP_ID				int				IDENTITY (1,1),
SEASON						int				NOT NULL,
CHAMPIONSHIP_NAME			nvarchar(50),
REGION_ID					int,
SPORT_ID					int,
IS_CLUBS					int				NOT NULL,
LAST_REGISTRATION_DATE		datetime,
START_DATE					datetime,
END_DATE					datetime,
ALT_START_DATE				datetime,
ALT_END_DATE				datetime,
FINALS_DATE					datetime,
ALT_FINALS_DATE				datetime,
RULESET_ID					int,
IS_OPEN						int,		--0/1 for central championships only.
CHAMPIONSHIP_STATUS			int				NOT NULL	DEFAULT 0,  --0/1/2
CHAMPIONSHIP_SUPERVISOR		int,
STANDARD_CHAMPIONSHIP_ID	int,
DATE_LAST_MODIFIED DATETIME,
DATE_DELETED datetime,
timestamp,
CONSTRAINT PK_CHAMPIONSHIPS PRIMARY KEY(CHAMPIONSHIP_ID),
CONSTRAINT FK_CHAMPIONSHIPS_SEASON FOREIGN KEY(SEASON)
	REFERENCES SEASONS(SEASON),
CONSTRAINT FK_CHAMPIONSHIPS_REGION FOREIGN KEY(REGION_ID)
	REFERENCES REGIONS(REGION_ID),
CONSTRAINT UN_CHAMPIONSHIPS_NAME UNIQUE(SEASON, REGION_ID, CHAMPIONSHIP_NAME, DATE_DELETED),
CONSTRAINT FK_CHAMPIONSHIPS_SPORT FOREIGN KEY(SPORT_ID)
	REFERENCES SPORTS(SPORT_ID),
CONSTRAINT FK_CHAMPIONSHIPS_RULESET FOREIGN KEY(RULESET_ID)
	REFERENCES RULESETS(RULESET_ID),
CONSTRAINT FK_CHAMPIONSHIPS_SUPERVISOR FOREIGN KEY(CHAMPIONSHIP_SUPERVISOR)
	REFERENCES USERS(USER_ID),
CONSTRAINT FK_CHAMPIONSHIPS_STANDARD FOREIGN KEY(STANDARD_CHAMPIONSHIP_ID)
	REFERENCES STANDARD_CHAMPIONSHIPS(STANDARD_CHAMPIONSHIP_ID),
CONSTRAINT CHK_CHAMPIONSHIP_CLUB CHECK (IS_CLUBS = 0 OR IS_CLUBS = 1)
)
GO

-- =======    CHAMPIONSHIP_CATEGORIES TABLE   ======
CREATE TABLE CHAMPIONSHIP_CATEGORIES (
CHAMPIONSHIP_CATEGORY_ID	int		IDENTITY (1,1),
CHAMPIONSHIP_ID				int		NOT NULL,
CATEGORY					int		NOT NULL,
REGISTRATION_PRICE			real			NOT NULL	DEFAULT 0,
DATE_LAST_MODIFIED DATETIME,
DATE_DELETED datetime,
timestamp,
CONSTRAINT PK_CHAMPIONSHIP_CATEGORIES PRIMARY KEY(CHAMPIONSHIP_CATEGORY_ID),
CONSTRAINT FK_CHAMPIONCAT_CHAMPIONSHIP FOREIGN KEY(CHAMPIONSHIP_ID)
	REFERENCES CHAMPIONSHIPS(CHAMPIONSHIP_ID), 
CONSTRAINT CHK_CHAMPIONSHIP_REG_PRICE CHECK 
	(REGISTRATION_PRICE >= 0 AND REGISTRATION_PRICE <= 999999)
)
GO

-- =======    CHAMPIONSHIP_REGIONS TABLE   ======
CREATE TABLE CHAMPIONSHIP_REGIONS (
CHAMPIONSHIP_REGION_ID	int		IDENTITY (1,1),
CHAMPIONSHIP_ID			int		NOT NULL,
REGION_ID				int		NOT NULL,
DATE_LAST_MODIFIED DATETIME,
DATE_DELETED datetime,
timestamp,
CONSTRAINT PK_CHAMPIONSHIP_REGIONS PRIMARY KEY(CHAMPIONSHIP_REGION_ID),
CONSTRAINT FK_CHAMPIONREGION_CHAMPIONSHIP FOREIGN KEY(CHAMPIONSHIP_ID)
	REFERENCES CHAMPIONSHIPS(CHAMPIONSHIP_ID),
CONSTRAINT FK_CHAMPIONREGION_REGION FOREIGN KEY(REGION_ID)
	REFERENCES REGIONS(REGION_ID)
)
GO

-- =======    CHAMPIONSHIP_PHASES   ======
CREATE TABLE CHAMPIONSHIP_PHASES (
CHAMPIONSHIP_CATEGORY_ID	int				NOT NULL,
PHASE						int				NOT NULL,
PHASE_NAME					nvarchar(100)	NOT NULL,
STATUS						int				NOT NULL, -- 0 plan, 1 ready, 2 started, 3 ended
DATE_LAST_MODIFIED DATETIME,
DATE_DELETED datetime,
timestamp,
CONSTRAINT PK_CHAMPIONSHIP_PHASES PRIMARY KEY(CHAMPIONSHIP_CATEGORY_ID, PHASE),
CONSTRAINT FK_CHAMPPHASE_CATEGORY FOREIGN KEY(CHAMPIONSHIP_CATEGORY_ID)
	REFERENCES CHAMPIONSHIP_CATEGORIES(CHAMPIONSHIP_CATEGORY_ID),
CONSTRAINT UN_CHAMPPHASE_NAME UNIQUE(CHAMPIONSHIP_CATEGORY_ID, PHASE_NAME, DATE_DELETED),
CONSTRAINT CHK_CHAMPPHASE_STATUS CHECK (STATUS IN (0, 1, 2, 3))
)
GO

-- =======    CHAMPIONSHIP_GROUPS   ======
CREATE TABLE CHAMPIONSHIP_GROUPS (
CHAMPIONSHIP_CATEGORY_ID	int				NOT NULL,
PHASE						int				NOT NULL,
NGROUP						int				NOT NULL,
GROUP_NAME					nvarchar(100)	NOT NULL,
STATUS						int				NOT NULL, -- 0 plan, 1 ready, 2 started, 3 ended
DATE_LAST_MODIFIED DATETIME,
DATE_DELETED datetime,
timestamp,
CONSTRAINT PK_CHAMPIONSHIP_GROUPS PRIMARY KEY(CHAMPIONSHIP_CATEGORY_ID, PHASE, NGROUP),
CONSTRAINT FK_CHAMPGROUP_PHASE FOREIGN KEY(CHAMPIONSHIP_CATEGORY_ID, PHASE)
	REFERENCES CHAMPIONSHIP_PHASES(CHAMPIONSHIP_CATEGORY_ID, PHASE),
CONSTRAINT UN_CHAMPGROUP_NAME UNIQUE(CHAMPIONSHIP_CATEGORY_ID, PHASE, GROUP_NAME, DATE_DELETED),
CONSTRAINT CHK_CHAMPGROUP_STATUS CHECK (STATUS IN (0, 1, 2, 3))
)
GO

-- =======    TEAMS TABLE   ======
CREATE TABLE TEAMS (
TEAM_ID						int				IDENTITY (1,1),
SCHOOL_ID					int				NOT NULL,
CHAMPIONSHIP_ID				int				NOT NULL,
CHAMPIONSHIP_CATEGORY_ID	int				NOT NULL,
STATUS						int				NOT NULL,
TEAM_INDEX					int				DEFAULT 0, 
CHARGE_ID					int,
TEAM_SUPERVISOR				int,
REGISTRATION_DATE			datetime	NOT NULL DEFAULT GETDATE(),
DATE_LAST_MODIFIED DATETIME,
DATE_DELETED datetime,
timestamp,
CONSTRAINT PK_TEAMS PRIMARY KEY(TEAM_ID),
CONSTRAINT UN_TEAMS_SCHOOL UNIQUE (CHAMPIONSHIP_CATEGORY_ID,SCHOOL_ID,TEAM_INDEX,DATE_DELETED),
CONSTRAINT FK_TEAMS_SCHOOL FOREIGN KEY(SCHOOL_ID)
	REFERENCES SCHOOLS(SCHOOL_ID),
CONSTRAINT FK_TEAMS_CHAMPION FOREIGN KEY(CHAMPIONSHIP_ID)
	REFERENCES CHAMPIONSHIPS(CHAMPIONSHIP_ID),
CONSTRAINT FK_TEAMS_CATEGORY FOREIGN KEY(CHAMPIONSHIP_CATEGORY_ID)
	REFERENCES CHAMPIONSHIP_CATEGORIES(CHAMPIONSHIP_CATEGORY_ID),
CONSTRAINT FK_TEAMS_CHARGE FOREIGN KEY(CHARGE_ID)
	REFERENCES CHARGES(CHARGE_ID),
CONSTRAINT FK_TEAMS_SUPERVISOR FOREIGN KEY(TEAM_SUPERVISOR)
	REFERENCES USERS(USER_ID)
)
GO

-- =======    PLAYERS TABLE    ======
CREATE TABLE  PLAYERS (
PLAYER_ID			int		IDENTITY (1,1),
STUDENT_ID			int		NOT NULL,
TEAM_ID				int		NOT NULL,
TEAM_NUMBER			int,
CHARGE_ID			int,
STATUS				int,
REMARKS				nvarchar(100), 
REGISTRATION_DATE	datetime	NOT NULL DEFAULT GETDATE(),
DATE_LAST_MODIFIED DATETIME,
DATE_DELETED datetime,
timestamp,
CONSTRAINT PK_PLAYERS PRIMARY KEY(PLAYER_ID),
CONSTRAINT FK_PLAYER_STUDENT FOREIGN KEY(STUDENT_ID)
	REFERENCES STUDENTS(STUDENT_ID),
CONSTRAINT FK_PLAYER_TEAM FOREIGN KEY(TEAM_ID)
	REFERENCES TEAMS(TEAM_ID),
CONSTRAINT FK_PLAYERS_CHARGE FOREIGN KEY(CHARGE_ID)
	REFERENCES CHARGES(CHARGE_ID),
CONSTRAINT UN_PLAYER_TEAM_STUDENT UNIQUE(TEAM_ID, STUDENT_ID, DATE_DELETED)
	)
GO

-- =======    CHAMPIONSHIP_GROUP_TEAMS   ======
CREATE TABLE CHAMPIONSHIP_GROUP_TEAMS (
CHAMPIONSHIP_CATEGORY_ID	int NOT NULL,
PHASE						int	NOT NULL,
NGROUP						int	NOT NULL,
POSITION					int NOT NULL,
PREVIOUS_GROUP				int,
PREVIOUS_POSITION			int,
TEAM_ID						int,
GAMES						int,
POINTS						int,
POINTS_AGAINST				int,
SMALL_POINTS				int,
SMALL_POINTS_AGAINST		int,
SCORE						real,
RESULT_POSITION				int,
DATE_LAST_MODIFIED DATETIME,
DATE_DELETED datetime,
timestamp,
CONSTRAINT PK_CHAMPIONSHIP_GROUP_TEAMS PRIMARY KEY(CHAMPIONSHIP_CATEGORY_ID, PHASE, NGROUP, POSITION),
CONSTRAINT FK_CHAMPGROUPTEAM_GROUP FOREIGN KEY(CHAMPIONSHIP_CATEGORY_ID, PHASE, NGROUP)
	REFERENCES CHAMPIONSHIP_GROUPS(CHAMPIONSHIP_CATEGORY_ID, PHASE, NGROUP),
CONSTRAINT FK_CHAMPGROUPTEAM_TEAM FOREIGN KEY(TEAM_ID)
	REFERENCES TEAMS(TEAM_ID),
CONSTRAINT CHK_CHAMPGROUP_TEAM CHECK (
	(PREVIOUS_GROUP IS NOT NULL AND PREVIOUS_POSITION IS NOT NULL) OR
	(TEAM_ID IS NOT NULL)),
CONSTRAINT CHK_CHAMPGROUP_SCORE CHECK (
	(TEAM_ID IS NOT NULL) OR (GAMES IS NULL AND SCORE IS NULL))
)
GO

-- =======    CHAMPIONSHIP_ROUNDS   ======
-- The table devides the championship matches to rounds
-- The matches are for match type sports only
CREATE TABLE CHAMPIONSHIP_ROUNDS (
CHAMPIONSHIP_CATEGORY_ID	int				NOT NULL,
PHASE						int				NOT NULL,
NGROUP						int				NOT NULL,
ROUND						int				NOT NULL,
ROUND_NAME					nvarchar(100)	NOT NULL,
STATUS						int				NOT NULL, -- 0 plan, 1 ready, 2 started, 3 ended
DATE_LAST_MODIFIED DATETIME,
DATE_DELETED datetime,
timestamp,
CONSTRAINT PK_CHAMPIONSHIP_ROUNDS PRIMARY KEY(CHAMPIONSHIP_CATEGORY_ID, PHASE, NGROUP, ROUND),
CONSTRAINT FK_CHAMPROUND_GROUP FOREIGN KEY(CHAMPIONSHIP_CATEGORY_ID, PHASE, NGROUP)
	REFERENCES CHAMPIONSHIP_GROUPS(CHAMPIONSHIP_CATEGORY_ID, PHASE, NGROUP),
CONSTRAINT UN_CHAMPROUND_NAME UNIQUE(CHAMPIONSHIP_CATEGORY_ID, PHASE, NGROUP, ROUND_NAME, DATE_DELETED),
CONSTRAINT CHK_CHAMPROUND_STATUS CHECK (STATUS IN (0, 1, 2, 3))
)
GO

-- =======    CHAMPIONSHIP_MATCHES TABLE   ======
-- The table contains all matches for a group in a phase
-- The matches are for match type sports only
CREATE TABLE CHAMPIONSHIP_MATCHES (
CHAMPIONSHIP_CATEGORY_ID	int	NOT NULL,
PHASE						int	NOT NULL,
NGROUP						int	NOT NULL,
ROUND						int	NOT NULL,
CYCLE						int	NOT NULL DEFAULT 0,
MATCH						int NOT NULL,
TEAM_A						int NOT NULL,
TEAM_B						int NOT NULL,
TIME						datetime,
FACILITY_ID					int,
COURT_ID					int,
TEAM_A_SCORE				real,
TEAM_B_SCORE				real,
RESULT						int, -- 0 tie, 1 teamA win, 2 teamB win, 3 teamA technical win, 4 teamB technical win
PARTS_RESULT				nvarchar(2000),
DATE_LAST_MODIFIED DATETIME,
DATE_DELETED datetime,
timestamp,
CONSTRAINT PK_CHAMPIONSHIP_MATCHES PRIMARY KEY(CHAMPIONSHIP_CATEGORY_ID, PHASE, NGROUP, ROUND, MATCH),
CONSTRAINT FK_CHAMPMATCH_ROUND FOREIGN KEY(CHAMPIONSHIP_CATEGORY_ID, PHASE, NGROUP, ROUND)
	REFERENCES CHAMPIONSHIP_ROUNDS(CHAMPIONSHIP_CATEGORY_ID, PHASE, NGROUP, ROUND),
CONSTRAINT FK_CHAMPMATCH_TEAMA FOREIGN KEY(CHAMPIONSHIP_CATEGORY_ID, PHASE, NGROUP, TEAM_A)
	REFERENCES CHAMPIONSHIP_GROUP_TEAMS(CHAMPIONSHIP_CATEGORY_ID, PHASE, NGROUP, POSITION),
CONSTRAINT FK_CHAMPMATCH_TEAMB FOREIGN KEY(CHAMPIONSHIP_CATEGORY_ID, PHASE, NGROUP, TEAM_B)
	REFERENCES CHAMPIONSHIP_GROUP_TEAMS(CHAMPIONSHIP_CATEGORY_ID, PHASE, NGROUP, POSITION),
CONSTRAINT FK_CHAMPMATCH_FACILITY FOREIGN KEY(FACILITY_ID)
	REFERENCES FACILITIES(FACILITY_ID),
CONSTRAINT FK_CHAMPMATCH_COURT FOREIGN KEY(COURT_ID)
	REFERENCES COURTS(COURT_ID),
CONSTRAINT CHK_CHAMPMATCH_COURFAC CHECK (FACILITY_ID IS NOT NULL OR COURT_ID IS NULL),
CONSTRAINT CHK_CHAMPMATCH_RESULT CHECK (RESULT IN (0, 1, 2, 3, 4))
)
GO

-- =======    CHAMPIONSHIP_COMPETITIONS TABLE   ======
-- The table contains all competitions in a group in a phase
-- The competitions are for competition type sports only
CREATE TABLE CHAMPIONSHIP_COMPETITIONS (
CHAMPIONSHIP_CATEGORY_ID	int	NOT NULL,
PHASE						int	NOT NULL,
NGROUP						int	NOT NULL,
COMPETITION					int	NOT NULL,
SPORT_FIELD_ID				int NOT NULL,
TIME						datetime,
FACILITY_ID					int,
COURT_ID					int,
LANE_COUNT					int,
DATE_LAST_MODIFIED DATETIME,
DATE_DELETED datetime,
timestamp,
CONSTRAINT PK_CHAMPIONSHIP_COMPETITIONS PRIMARY KEY(CHAMPIONSHIP_CATEGORY_ID, PHASE, NGROUP, COMPETITION),
CONSTRAINT FK_CHAMPCOMPT_GROUP FOREIGN KEY(CHAMPIONSHIP_CATEGORY_ID, PHASE, NGROUP)
	REFERENCES CHAMPIONSHIP_GROUPS(CHAMPIONSHIP_CATEGORY_ID, PHASE, NGROUP),
CONSTRAINT FK_CHAMPCOMPT_FIELD FOREIGN KEY(SPORT_FIELD_ID)
	REFERENCES SPORT_FIELDS(SPORT_FIELD_ID),
CONSTRAINT FK_CHAMPCOMPT_FACILITY FOREIGN KEY(FACILITY_ID)
	REFERENCES FACILITIES(FACILITY_ID),
CONSTRAINT FK_CHAMPCOMPT_COURT FOREIGN KEY(COURT_ID)
	REFERENCES COURTS(COURT_ID)
)
GO

-- =======    CHAMPIONSHIP_COMPETITION_HEATS TABLE   ======
-- The table devide championship competitions competitors into heats
-- The competition heats are for competition type sports only
CREATE TABLE CHAMPIONSHIP_COMPETITION_HEATS (
CHAMPIONSHIP_CATEGORY_ID	int	NOT NULL,
PHASE						int	NOT NULL,
NGROUP						int	NOT NULL,
COMPETITION					int	NOT NULL,
HEAT						int NOT NULL,
TIME						datetime,
FACILITY_ID					int,
COURT_ID					int,
DATE_LAST_MODIFIED DATETIME,
DATE_DELETED datetime,
timestamp,
CONSTRAINT PK_CHAMPIONSHIP_COMPETITION_HEATS PRIMARY KEY(CHAMPIONSHIP_CATEGORY_ID, PHASE, NGROUP, COMPETITION, HEAT),
CONSTRAINT FK_CHAMPHEAT_COMPETITION FOREIGN KEY(CHAMPIONSHIP_CATEGORY_ID, PHASE, NGROUP, COMPETITION)
	REFERENCES CHAMPIONSHIP_COMPETITIONS(CHAMPIONSHIP_CATEGORY_ID, PHASE, NGROUP, COMPETITION),
CONSTRAINT FK_CHAMPHEAT_FACILITY FOREIGN KEY(FACILITY_ID)
	REFERENCES FACILITIES(FACILITY_ID),
CONSTRAINT FK_CHAMPHEAT_COURT FOREIGN KEY(COURT_ID)
	REFERENCES COURTS(COURT_ID)
)
GO

-- =======    CHAMPIONSHIP_COMPETITION_COMPETITORS TABLE   ======
-- The table contains the compertitors of each heat or competition
-- The competitors are for competition type sports only
CREATE TABLE CHAMPIONSHIP_COMPETITION_COMPETITORS (
CHAMPIONSHIP_CATEGORY_ID	int	NOT NULL,
PHASE						int	NOT NULL,
NGROUP						int	NOT NULL,
COMPETITION					int	NOT NULL,
COMPETITOR					int NOT NULL,
PLAYER_ID					int,
HEAT						int,
POSITION					int,
RESULT_POSITION				int,
RESULT						nvarchar(20),
SCORE						int,
CUSTOM_POSITION				int,
DATE_LAST_MODIFIED DATETIME,
DATE_DELETED datetime,
timestamp,
CONSTRAINT PK_CHAMPIONSHIP_COMPETITION_COMPETITORS PRIMARY KEY(CHAMPIONSHIP_CATEGORY_ID, PHASE, NGROUP, COMPETITION, COMPETITOR),
CONSTRAINT FK_CHAMPCOMPETITOR_COMPETITION FOREIGN KEY(CHAMPIONSHIP_CATEGORY_ID, PHASE, NGROUP, COMPETITION)
	REFERENCES CHAMPIONSHIP_COMPETITIONS(CHAMPIONSHIP_CATEGORY_ID, PHASE, NGROUP, COMPETITION),
CONSTRAINT FK_CHAMPCOMPETITOR_HEAT FOREIGN KEY(CHAMPIONSHIP_CATEGORY_ID, PHASE, NGROUP, COMPETITION, HEAT)
	REFERENCES CHAMPIONSHIP_COMPETITION_HEATS(CHAMPIONSHIP_CATEGORY_ID, PHASE, NGROUP, COMPETITION, HEAT),
CONSTRAINT FK_CHAMPCOMPETITOR_PLAYER FOREIGN KEY(PLAYER_ID)
	REFERENCES PLAYERS(PLAYER_ID),
CONSTRAINT CHK_COMPETITOR_SCORE CHECK 
	((SCORE >= 0) AND (SCORE <= 100))
)
GO

-- =======    PENDING_TEAMS  TABLE    ======
CREATE TABLE  PENDING_TEAMS  (
PENDING_TEAM_ID		int		IDENTITY (1,1),
USER_ID				int		NOT NULL,	--user who asked to register the team.
SCHOOL_ID			int		NOT NULL,	--school to which to register the team.
CHAMP_CATEGORY_ID	int		NOT NULL,	--category for which to register the team.
TEAM_INDEX			int,				--index of team to register.
DATE_LAST_MODIFIED DATETIME,
DATE_DELETED datetime,
timestamp,
CONSTRAINT PK_PENDING_TEAMS PRIMARY KEY(PENDING_TEAM_ID),
CONSTRAINT FK_PENDING_TEAMS_USER FOREIGN KEY(USER_ID)
	REFERENCES USERS(USER_ID),
CONSTRAINT FK_PENDING_TEAMS_SCHOOL FOREIGN KEY(SCHOOL_ID)
	REFERENCES SCHOOLS(SCHOOL_ID),
CONSTRAINT FK_PENDING_TEAMS_CATEGORY FOREIGN KEY(CHAMP_CATEGORY_ID)
	REFERENCES CHAMPIONSHIP_CATEGORIES(CHAMPIONSHIP_CATEGORY_ID))	
GO

-- =======    PENDING_PLAYERS  TABLE    ======
CREATE TABLE  PENDING_PLAYERS  (
PENDING_PLAYER_ID	int		IDENTITY (1,1),
USER_ID				int		NOT NULL,	--user who asked to register the player.
TEAM_ID				int		NOT NULL,	--team for which to register the player.
STUDENT_ID			int		NOT NULL,	--student id of player to register.
PLAYER_NUMBER		int,				--player number of player to register.
STATUS				int		NOT NULL DEFAULT 1, 
DATE_LAST_MODIFIED DATETIME,
DATE_DELETED datetime,
timestamp,
CONSTRAINT PK_PENDING_PLAYERS PRIMARY KEY(PENDING_PLAYER_ID),
CONSTRAINT FK_PENDING_PLAYERS_USER FOREIGN KEY(USER_ID)
	REFERENCES USERS(USER_ID),
CONSTRAINT FK_PENDING_PLAYERS_TEAM FOREIGN KEY(TEAM_ID)
	REFERENCES TEAMS(TEAM_ID),
CONSTRAINT FK_PENDING_PLAYERS_STUDENT FOREIGN KEY(STUDENT_ID)
	REFERENCES STUDENTS(STUDENT_ID))	
GO

-- =======    STUDENT_CARDS TABLE   ======
CREATE TABLE STUDENT_CARDS (
CARD_ID				int			IDENTITY (1,1),		--primary key
STUDENT_ID			int			NOT NULL,			--student to which the card belongs
SPORT_ID			int			NOT NULL,			--type of sport
ISSUE_DATE			datetime	NOT NULL,			--time the card was issued
ISSUE_SEASON		int			NOT NULL,			--season in which card was issued
STICKER_DATE		datetime,						--time the last sticker was given
STICKER_SEASON		int,							--season in which last sticker given
DATE_LAST_MODIFIED DATETIME,
DATE_DELETED datetime,
timestamp,
CONSTRAINT PK_STUDENT_CARDS PRIMARY KEY(CARD_ID),
CONSTRAINT UN_CARD_STUDENT_SPORT UNIQUE(STUDENT_ID,SPORT_ID,DATE_DELETED),
CONSTRAINT FK_STUDENTCARD_STUDENT FOREIGN KEY(STUDENT_ID)
	REFERENCES STUDENTS(STUDENT_ID),
CONSTRAINT FK_STUDENTCARD_SPORT FOREIGN KEY(SPORT_ID)
	REFERENCES SPORTS(SPORT_ID),
CONSTRAINT FK_STUDENTCARD_CARD_SEASON FOREIGN KEY(ISSUE_SEASON)
	REFERENCES SEASONS(SEASON),	
CONSTRAINT FK_STUDENTCARD_STICKER_SEASON FOREIGN KEY(STICKER_SEASON)
	REFERENCES SEASONS(SEASON))
GO 

-- =======    LOG_TABLE TABLE   ======
CREATE TABLE LOG_TABLE (
LOG_ID			int				IDENTITY (1,1),
USER_ID			int				NOT NULL,
LOG_DATE		datetime		NOT NULL,
DESCRIPTION		nvarchar(255),
VERSION_USED	real			NOT NULL,
DATE_LAST_MODIFIED DATETIME,
DATE_DELETED datetime,
timestamp,
CONSTRAINT PK_LOG_TABLE PRIMARY KEY(LOG_ID),
CONSTRAINT FK_LOG_USER FOREIGN KEY(USER_ID) REFERENCES USERS(USER_ID))
GO

-- =======    EQUIPMENT_TYPES TABLE   ======
CREATE TABLE EQUIPMENT_TYPES (
EQUIPMENT_TYPE_ID			int				IDENTITY(1, 1),
EQUIPMENT_NAME				nvarchar(100)	NOT NULL,
EQUIPMENT_BASE_PRICE		float			NOT NULL default 0,
EQUIPMENT_TYPE_TYPE			int NOT NULL, --0 General/1 Region/2 Sport/3 Championship/4 Category
DATE_LAST_MODIFIED DATETIME,
DATE_DELETED datetime,
timestamp,
CONSTRAINT PK_EQUIPMENT_TYPE PRIMARY KEY(EQUIPMENT_TYPE_ID),
CONSTRAINT UN_EQUIPMENT_NAME UNIQUE(EQUIPMENT_NAME, DATE_DELETED),
CONSTRAINT CHK_EQUIPMENT_TYPE CHECK(EQUIPMENT_TYPE_TYPE>=0 AND EQUIPMENT_TYPE_TYPE<5)
)
GO 

-- =======    EQUIPMENT TABLE   ======
CREATE TABLE EQUIPMENT (
EQUIPMENT_ID				int				IDENTITY(1, 1),
EQUIPMENT_TYPE_ID			int				NOT NULL,
EQUIPMENT_REGION_ID			int,
EQUIPMENT_SPORT_ID			int,
EQUIPMENT_CHAMPIONSHIP_ID	int,
EQUIPMENT_CATEGORY_ID		int,
EQUIPMENT_AMOUNT			int				NOT NULL default 0,
EQUIPMENT_PRICE				float			NOT NULL default 0,
EQUIPMENT_ORDER_DATE		datetime		NOT NULL default GETDATE(),
DATE_LAST_MODIFIED DATETIME,
DATE_DELETED datetime,
timestamp,
CONSTRAINT PK_EQUIPMENT PRIMARY KEY(EQUIPMENT_ID),
CONSTRAINT FK_EQUIPMENT_REGION FOREIGN KEY (EQUIPMENT_REGION_ID)
	REFERENCES REGIONS(REGION_ID),
CONSTRAINT FK_EQUIPMENT_SPORT FOREIGN KEY (EQUIPMENT_SPORT_ID)
	REFERENCES SPORTS(SPORT_ID),
CONSTRAINT FK_EQUIPMENT_CHAMPIONSHIP FOREIGN KEY (EQUIPMENT_CHAMPIONSHIP_ID)
	REFERENCES CHAMPIONSHIPS(CHAMPIONSHIP_ID),
CONSTRAINT FK_EQUIPMENT_CATEGORY FOREIGN KEY (EQUIPMENT_CATEGORY_ID)
	REFERENCES CHAMPIONSHIP_CATEGORIES(CHAMPIONSHIP_CATEGORY_ID)
)
GO

-- =======    ISF_PAYMENTS TABLE   ======
CREATE TABLE ISF_PAYMENTS (
ISF_PAYMENT_ID			int				IDENTITY(1, 1),
EQUIPMENT_ID			int,
PAYMENT_SUM				float			NOT NULL default 0,
PAYMENT_DESCRIPTION		nvarchar(255)	NOT NULL default '',
PAYMENT_DATE			datetime		NOT NULL default GETDATE(),
PAYMENT_TYPE			int				NOT NULL,
PAID_BY					int				NOT NULL,
DATE_LAST_MODIFIED DATETIME,
DATE_DELETED datetime,
timestamp,
CONSTRAINT PK_ISF_PAYMENT PRIMARY KEY(ISF_PAYMENT_ID),
CONSTRAINT FK_ISF_PAYMENT_EQUIPMENT FOREIGN KEY (EQUIPMENT_ID)
	REFERENCES EQUIPMENT(EQUIPMENT_ID),
CONSTRAINT FK_ISF_PAYMENT_USER FOREIGN KEY (PAID_BY)
	REFERENCES USERS(USER_ID)
)
GO

-- =======    SPORTSMAN_FORMS TABLE   ======
CREATE TABLE SPORTSMAN_FORMS (
SPORTSMAN_FORM_ID		int				IDENTITY(1, 1),
FORM_CLASSNAME			nvarchar(200)	NOT NULL,
FORM_DESCRIPTION		nvarchar(255)	NOT NULL,
CONSTRAINT PK_SPORTSMAN_FORMS PRIMARY KEY(SPORTSMAN_FORM_ID),
CONSTRAINT UN_SPORTSMAN_FORM_CLASS UNIQUE(FORM_CLASSNAME)
)
GO 

-- =======    SPORTSMAN_PERMISSIONS TABLE   ======
CREATE TABLE SPORTSMAN_PERMISSIONS (
SPORTSMAN_PERMISSION_ID		int			IDENTITY(1, 1),
USER_ID						int			NOT NULL,
SPORTSMAN_FORM_ID			int,
PERMISSION_TYPE				int			NOT NULL,	--0 none,1 readonly,2 full.
CONSTRAINT PK_SPORTSMAN_PERMISSIONS PRIMARY KEY(SPORTSMAN_PERMISSION_ID),
CONSTRAINT UN_SPORTSMAN_PERMISSION UNIQUE(USER_ID, SPORTSMAN_FORM_ID),
CONSTRAINT FK_SPORTSMAN_PERMISSION_USER FOREIGN KEY (USER_ID)
	REFERENCES USERS(USER_ID),
CONSTRAINT FK_SPORTSMAN_PERMISSION_FORM FOREIGN KEY (SPORTSMAN_FORM_ID)
	REFERENCES SPORTSMAN_FORMS(SPORTSMAN_FORM_ID)
)
GO

INSERT INTO SPORTSMAN_FORMS (FORM_CLASSNAME, FORM_DESCRIPTION)
VALUES ('Sportsman.Views.BugsTableView', 'עריכת הערות')
GO

INSERT INTO SPORTSMAN_FORMS (FORM_CLASSNAME, FORM_DESCRIPTION)
VALUES ('Sportsman.Views.CalendarView', 'לוח שנה')
GO

INSERT INTO SPORTSMAN_FORMS (FORM_CLASSNAME, FORM_DESCRIPTION)
VALUES ('Sportsman.Views.ChampionshipsTableView', 'ניהול אליפויות')
GO

INSERT INTO SPORTSMAN_FORMS (FORM_CLASSNAME, FORM_DESCRIPTION)
VALUES ('Sportsman.Views.ChargesTableView', 'ניהול חיובי בתי ספר')
GO

INSERT INTO SPORTSMAN_FORMS (FORM_CLASSNAME, FORM_DESCRIPTION)
VALUES ('Sportsman.Views.CitiesTableView', 'הגדרת יישובים')
GO

INSERT INTO SPORTSMAN_FORMS (FORM_CLASSNAME, FORM_DESCRIPTION)
VALUES ('Sportsman.Views.CourtTypesTableView', 'ניהול סוגי מגרשים')
GO

INSERT INTO SPORTSMAN_FORMS (FORM_CLASSNAME, FORM_DESCRIPTION)
VALUES ('Sportsman.Views.EquipmentTableView', 'ניהול ציוד התאחדות')
GO

INSERT INTO SPORTSMAN_FORMS (FORM_CLASSNAME, FORM_DESCRIPTION)
VALUES ('Sportsman.Views.EquipmentTypesTableView', 'ניהול סוגי ציוד')
GO

INSERT INTO SPORTSMAN_FORMS (FORM_CLASSNAME, FORM_DESCRIPTION)
VALUES ('Sportsman.Views.FacilitiesTableView', 'ניהול מתקנים')
GO

INSERT INTO SPORTSMAN_FORMS (FORM_CLASSNAME, FORM_DESCRIPTION)
VALUES ('Sportsman.Views.GameBoardsTableView', 'רשימת לוחות משחקים')
GO

INSERT INTO SPORTSMAN_FORMS (FORM_CLASSNAME, FORM_DESCRIPTION)
VALUES ('Sportsman.Views.IsfPaymentsTableView', 'ניהול תשלומי התאחדות')
GO

INSERT INTO SPORTSMAN_FORMS (FORM_CLASSNAME, FORM_DESCRIPTION)
VALUES ('Sportsman.Views.LogTableView', 'ניהול מעקב משתמשים')
GO

INSERT INTO SPORTSMAN_FORMS (FORM_CLASSNAME, FORM_DESCRIPTION)
VALUES ('Sportsman.Views.MessagesTableView', 'הודעות מערכת')
GO

INSERT INTO SPORTSMAN_FORMS (FORM_CLASSNAME, FORM_DESCRIPTION)
VALUES ('Sportsman.Views.PaymentsTableView', 'ניהול תשלומי בית ספר')
GO

INSERT INTO SPORTSMAN_FORMS (FORM_CLASSNAME, FORM_DESCRIPTION)
VALUES ('Sportsman.Views.PhasePatternsTableView', 'רשימת תבניות שלבים')
GO

INSERT INTO SPORTSMAN_FORMS (FORM_CLASSNAME, FORM_DESCRIPTION)
VALUES ('Sportsman.Views.PlayersTableView', 'רישום שחקנים')
GO

INSERT INTO SPORTSMAN_FORMS (FORM_CLASSNAME, FORM_DESCRIPTION)
VALUES ('Sportsman.Views.ProductsTableView', 'עריכת תעריפי בסיס')
GO

INSERT INTO SPORTSMAN_FORMS (FORM_CLASSNAME, FORM_DESCRIPTION)
VALUES ('Sportsman.Views.RefereesTableView', 'ניהול שופטים')
GO

INSERT INTO SPORTSMAN_FORMS (FORM_CLASSNAME, FORM_DESCRIPTION)
VALUES ('Sportsman.Views.RegionsTableView', 'עריכת מחוזות')
GO

INSERT INTO SPORTSMAN_FORMS (FORM_CLASSNAME, FORM_DESCRIPTION)
VALUES ('Sportsman.Views.RuleSersTableView', 'רשימת תקנונים')
GO

INSERT INTO SPORTSMAN_FORMS (FORM_CLASSNAME, FORM_DESCRIPTION)
VALUES ('Sportsman.Views.SchoolsTableView', 'ניהול בתי ספר')
GO

INSERT INTO SPORTSMAN_FORMS (FORM_CLASSNAME, FORM_DESCRIPTION)
VALUES ('Sportsman.Views.ScoreRangeTableView', 'ניהול ניקוד תוצאות')
GO

INSERT INTO SPORTSMAN_FORMS (FORM_CLASSNAME, FORM_DESCRIPTION)
VALUES ('Sportsman.Views.SportFieldsTableView', 'עריכת מקצועות וסוגי מקצועות')
GO

INSERT INTO SPORTSMAN_FORMS (FORM_CLASSNAME, FORM_DESCRIPTION)
VALUES ('Sportsman.Views.SportsTableView', 'עריכת ענפי ספורט')
GO

INSERT INTO SPORTSMAN_FORMS (FORM_CLASSNAME, FORM_DESCRIPTION)
VALUES ('Sportsman.Views.StandardChampionshipsTableView', 'ניהול אליפויות קבועות')
GO

INSERT INTO SPORTSMAN_FORMS (FORM_CLASSNAME, FORM_DESCRIPTION)
VALUES ('Sportsman.Views.StudentsTableView', 'ניהול תלמידים')
GO

INSERT INTO SPORTSMAN_FORMS (FORM_CLASSNAME, FORM_DESCRIPTION)
VALUES ('Sportsman.Views.TeamsTableView', 'רישום קבוצות')
GO

INSERT INTO SPORTSMAN_FORMS (FORM_CLASSNAME, FORM_DESCRIPTION)
VALUES ('Sportsman.Views.UsersTableView', 'ניהול משתמשים')
GO

INSERT INTO SPORTSMAN_FORMS (FORM_CLASSNAME, FORM_DESCRIPTION)
VALUES ('Sportsman.Producer.CompetitionChampionshipEditorView', 'ניהול אליפויות מסוג תחרות')
GO

INSERT INTO SPORTSMAN_FORMS (FORM_CLASSNAME, FORM_DESCRIPTION)
VALUES ('Sportsman.Producer.GameBoardEditorView', 'עריכת לוחות משחקים')
GO

INSERT INTO SPORTSMAN_FORMS (FORM_CLASSNAME, FORM_DESCRIPTION)
VALUES ('Sportsman.Producer.MatchChampionshipEditorView', 'ניהול אליפויות מסוג התמודדות')
GO

INSERT INTO SPORTSMAN_FORMS (FORM_CLASSNAME, FORM_DESCRIPTION)
VALUES ('Sportsman.Producer.PhasePatternEditorView', 'עריכת תבניות שלבים')
GO

INSERT INTO SPORTSMAN_FORMS (FORM_CLASSNAME, FORM_DESCRIPTION)
VALUES ('Sportsman.Producer.PlayerCardBuildForm', 'בניית כרטיסי שחקן')
GO

INSERT INTO SPORTSMAN_FORMS (FORM_CLASSNAME, FORM_DESCRIPTION)
VALUES ('Sportsman.Producer.RulesetEditorView', 'עריכת תקנונים')
GO

INSERT INTO SPORTSMAN_FORMS (FORM_CLASSNAME, FORM_DESCRIPTION)
VALUES ('Sport.UI.Dialogs.PrintForm', 'הדפסות כלליות')
GO

INSERT INTO SPORTSMAN_FORMS (FORM_CLASSNAME, FORM_DESCRIPTION)
VALUES ('Sportsman.Forms.PermissionsForm', 'ניהול הרשאות')
GO

INSERT INTO SPORTSMAN_FORMS (FORM_CLASSNAME, FORM_DESCRIPTION)
VALUES ('Sportsman.Details.StudentDetails', 'פרטי תלמידים')
GO

INSERT INTO SPORTSMAN_FORMS (FORM_CLASSNAME, FORM_DESCRIPTION)
VALUES ('Sportsman.Producer.GamesReportView', 'דו\"ח אירועים')
GO

-- =======    USER_ACTIONS TABLE   ======
CREATE TABLE USER_ACTIONS (
USER_ACTION_ID	int				IDENTITY (1,1),
ACTION_TYPE		int				NOT NULL,
USER_ID			int				NOT NULL,
ACTION_DATE		datetime		NOT NULL,
DESCRIPTION		nvarchar(255),
VERSION			real			NOT NULL,
CONSTRAINT PK_USER_ACTION PRIMARY KEY(USER_ACTION_ID)
)
GO

-- =======    FLASH_NEWS TABLE   ======
CREATE TABLE ISF_FLASH_NEWS (
FLASH_NEWS_ID		int				IDENTITY(1, 1),
SUBMISSION_TIME		datetime		NOT NULL DEFAULT GETDATE(),
SUBMITTED_BY		int				NOT NULL,
NEWS_DESCRIPTION	nvarchar(1024)	NOT NULL,
CONSTRAINT PK_FLASH_NEWS PRIMARY KEY(FLASH_NEWS_ID),
CONSTRAINT FK_FLASH_NEWS FOREIGN KEY (SUBMITTED_BY)
	REFERENCES USERS(USER_ID)
)
GO

-- =======    ISF_ARTICLES TABLE   ======
CREATE TABLE ISF_ARTICLES (
ARTICLE_ID			int				IDENTITY(1, 1),
SUBMISSION_TIME		datetime		NOT NULL DEFAULT GETDATE(),
SUBMITTED_BY		int				NOT NULL,
ARTICLE_DESCRIPTION	nvarchar(1024)	NOT NULL,
ARTICLE_FILE_NAME	nvarchar(100), --for text longer than 1024 characters.
ARTICLE_IMAGE_NAME	nvarchar(50),
ARTICLE_CAPTION		nvarchar(100),
ARTICLE_SUB_CAPTION nvarchar(255),
CONSTRAINT PK_ARTICLES PRIMARY KEY(ARTICLE_ID),
CONSTRAINT UN_ARTICLE_FILE UNIQUE(ARTICLE_ID, ARTICLE_FILE_NAME),
CONSTRAINT FK_ARTICLES FOREIGN KEY (SUBMITTED_BY)
	REFERENCES USERS(USER_ID)
)
GO

-- =======    WEBSITE_VISITORS TABLE   ======
CREATE TABLE WEBSITE_VISITORS (
VISITOR_ID		int				IDENTITY(1, 1),
IP_ADDRESS		nvarchar(15)	NOT NULL,
USER_AGENT		nvarchar(150),
CONSTRAINT PK_WEBSITE_VISITORS PRIMARY KEY(VISITOR_ID),
CONSTRAINT UN_VISITOR_IP_AGENT UNIQUE(IP_ADDRESS, USER_AGENT)
)
GO

-- =======    WEBSITE_HIT_LOG TABLE   ======
CREATE TABLE WEBSITE_HIT_LOG (
HIT_LOG_ID			int				IDENTITY(1, 1),
VISITOR_ID			int				NOT NULL,
PAGE_INDEX			int				NOT NULL,	--index in enum.
DATE_VISITED		datetime		NOT NULL DEFAULT GETDATE(),
QUERY_STRING_DATE	nvarchar(255),
FORM_DATA			nvarchar(255),
REFERER				nvarchar(255),
CONSTRAINT PK_WEBSITE_HIT_LOG PRIMARY KEY(HIT_LOG_ID),
CONSTRAINT FK_WEBSITE_VISITOR_HIT FOREIGN KEY (VISITOR_ID)
	REFERENCES WEBSITE_VISITORS(VISITOR_ID)
)
GO

-- =======    WEBSITE_PAGES TABLE   ======
CREATE TABLE WEBSITE_PAGES (
WEBSITE_PAGE_ID		int				IDENTITY(1, 1),
PAGE_CAPTION		nvarchar(255)	NOT NULL,
PAGE_CONTENTS		nvarchar(1024),
PAGE_AUTHOR			nvarchar(100),
AUTHOR_TITLE		nvarchar(150),
PAGE_ATTACHMENTS	nvarchar(255),
CONSTRAINT PK_WEBSITE_PAGES PRIMARY KEY(WEBSITE_PAGE_ID)
)
GO

-- =======    WEBSITE_POLLS TABLE   ======
CREATE TABLE WEBSITE_POLLS (
POLL_ID				int				IDENTITY(1, 1),
POLL_QUESTION		nvarchar(256)	NOT NULL,
POLL_SUBMIT_DATE	datetime		NOT NULL DEFAULT GETDATE(),
POLL_EXPIRE_DATE	datetime,
CONSTRAINT PK_WEBSITE_POLLS PRIMARY KEY(POLL_ID)
)
GO
-- =======    WEBSITE_POLLS_POSSIBLE_ANSWERS TABLE   ======
CREATE TABLE WEBSITE_POLLS_POSSIBLE_ANSWERS (
ANSWER_ID			int				IDENTITY(1, 1),
POLL_ID				int				NOT NULL,
ANSWER				nvarchar(1024)	NOT NULL,
CONSTRAINT PK_WEBSITE_POLLS_POSSIBLE_ANSWERS PRIMARY KEY(ANSWER_ID),
CONSTRAINT FK_POLLS_POSSIBLE_ANSWERS FOREIGN KEY(POLL_ID)
	REFERENCES WEBSITE_POLLS(POLL_ID)
)
GO
-- =======    WEBSITE_POLLS_RESULTS TABLE   ======
CREATE TABLE WEBSITE_POLLS_RESULTS (
RESULT_ID			int				IDENTITY(1, 1),
ANSWER_ID			int				NOT NULL,
VISITOR_IP			nvarchar(16)	NOT NULL,
SESSION_ID			nvarchar(128)	NOT NULL,
CONSTRAINT PK_WEBSITE_POLLS_RESULTS PRIMARY KEY(RESULT_ID),
CONSTRAINT FK_ANSWERS_RESULTS FOREIGN KEY(ANSWER_ID)
	REFERENCES WEBSITE_POLLS_POSSIBLE_ANSWERS(ANSWER_ID)
)
GO

-- =======    WEBSITE_BANNERS TABLE   ======
CREATE TABLE WEBSITE_BANNERS (
BANNER_ID		int				IDENTITY(1, 1),
URL_150_150		nvarchar(255)	NOT NULL,
URL_760_80		nvarchar(255)	NOT NULL,
DESCRIPTION		nvarchar(255)	NOT NULL,
DATE_DELETED	datetime,
CONSTRAINT PK_WEBSITE_BANNERS PRIMARY KEY(BANNER_ID)
)
GO

-- =======    WEBSITE_EVENTS TABLE   ======
CREATE TABLE WEBSITE_EVENTS (
EVENT_ID		int				IDENTITY(1, 1),
EVENT_DATE		datetime		NOT NULL,
DESCRIPTION		nvarchar(255)	NOT NULL,
URL				nvarchar(255),
DATE_DELETED	datetime,
CONSTRAINT PK_WEBSITE_EVENTS PRIMARY KEY(EVENT_ID)
)
GO

-- =======    WEBSITE_HIT_LOG_ARCHIVE TABLE   ======
CREATE TABLE WEBSITE_HIT_LOG_ARCHIVE (
HIT_LOG_ARCHIVE_ID	int				IDENTITY(1, 1),
PAGE_INDEX			int				NOT NULL,	--index in enum.
DATE_START			datetime,
DATE_END			datetime,
HIT_COUNT			int,
CONSTRAINT PK_WEBSITE_HIT_LOG_ARCHIVE PRIMARY KEY(HIT_LOG_ARCHIVE_ID)
)
GO