DROP TABLE CHAMPIONSHIP_MATCHES
DROP TABLE CHAMPIONSHIP_GROUP_TEAMS
DROP TABLE PENDING_PLAYERS
DROP TABLE CHAMPIONSHIP_COMPETITION_COMPETITORS
DROP TABLE PLAYERS
DROP TABLE TEAMS
DROP TABLE STUDENT_CARDS
DROP TABLE CHAMPIONSHIP_ROUNDS
DROP TABLE CHAMPIONSHIP_COMPETITION_HEATS
DROP TABLE CHAMPIONSHIP_COMPETITIONS
DROP TABLE CHAMPIONSHIP_GROUPS
DROP TABLE CHAMPIONSHIP_PHASES
DROP TABLE PENDING_TEAMS
DROP TABLE CHAMPIONSHIP_CATEGORIES
DROP TABLE CHAMPIONSHIP_REGIONS
DROP TABLE CHAMPIONSHIPS
DROP TABLE BUGS
ALTER TABLE SCHOOLS DROP CONSTRAINT FK_SCHOOL_CLUB_CHARGE
GO
DROP TABLE PAYMENTS
DROP TABLE CHARGES
DROP TABLE COURTS
DROP TABLE COURT_TYPES
DROP TABLE FACILITIES
DROP TABLE GAME_BOARDS
DROP TABLE MESSAGES
DROP TABLE PHASE_PATTERNS
DROP TABLE REFEREES
DROP TABLE STANDARD_CHAMPIONSHIP_CATEGORIES
DROP TABLE STANDARD_CHAMPIONSHIPS
DROP TABLE COMPETITOR_SCORE_RANGES
ALTER TABLE SPORTS DROP CONSTRAINT FK_SPORT_RULESET
GO
ALTER TABLE RULESETS DROP CONSTRAINT FK_RULESET_SPORT
GO
DROP TABLE SPORT_FIELDS
DROP TABLE SPORT_FIELD_TYPES
DROP TABLE SPORTS
DROP TABLE RULESETS
DROP TABLE COURT_TYPE_SPORTS
GO
DROP TABLE LOG_TABLE
GO