//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.2032
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 1.1.4322.2032.
// 
namespace Sportsman_Field.DataServices {
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="DataServiceSoap", Namespace="http://www.mir.co.il/DataService")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(FilterField[]))]
    public class DataService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        /// <remarks/>
        public DataService() {
            string urlSetting = System.Configuration.ConfigurationSettings.AppSettings["Sportsman_Field.DataServices.DataService"];
            if ((urlSetting != null)) {
                this.Url = string.Concat(urlSetting, "");
            }
            else {
                this.Url = "http://localhost/ISF/SportServices/DataService.asmx";
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.mir.co.il/DataService/GetEntities", RequestNamespace="http://www.mir.co.il/DataService", ResponseNamespace="http://www.mir.co.il/DataService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public Entity[] GetEntities(string entityName, [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)] FilterField[] filterFields, ref System.Decimal timestamp, out int[] deleted) {
            object[] results = this.Invoke("GetEntities", new object[] {
                        entityName,
                        filterFields,
                        timestamp});
            timestamp = ((System.Decimal)(results[1]));
            deleted = ((int[])(results[2]));
            return ((Entity[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetEntities(string entityName, FilterField[] filterFields, System.Decimal timestamp, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetEntities", new object[] {
                        entityName,
                        filterFields,
                        timestamp}, callback, asyncState);
        }
        
        /// <remarks/>
        public Entity[] EndGetEntities(System.IAsyncResult asyncResult, out System.Decimal timestamp, out int[] deleted) {
            object[] results = this.EndInvoke(asyncResult);
            timestamp = ((System.Decimal)(results[1]));
            deleted = ((int[])(results[2]));
            return ((Entity[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.mir.co.il/DataService/InsertEntity", RequestNamespace="http://www.mir.co.il/DataService", ResponseNamespace="http://www.mir.co.il/DataService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int InsertEntity(string entityName, object[] values) {
            object[] results = this.Invoke("InsertEntity", new object[] {
                        entityName,
                        values});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginInsertEntity(string entityName, object[] values, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("InsertEntity", new object[] {
                        entityName,
                        values}, callback, asyncState);
        }
        
        /// <remarks/>
        public int EndInsertEntity(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.mir.co.il/DataService/UpdateEntity", RequestNamespace="http://www.mir.co.il/DataService", ResponseNamespace="http://www.mir.co.il/DataService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool UpdateEntity(string entityName, object[] values) {
            object[] results = this.Invoke("UpdateEntity", new object[] {
                        entityName,
                        values});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginUpdateEntity(string entityName, object[] values, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("UpdateEntity", new object[] {
                        entityName,
                        values}, callback, asyncState);
        }
        
        /// <remarks/>
        public bool EndUpdateEntity(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.mir.co.il/DataService/DeleteEntity", RequestNamespace="http://www.mir.co.il/DataService", ResponseNamespace="http://www.mir.co.il/DataService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int DeleteEntity(string entityName, int id) {
            object[] results = this.Invoke("DeleteEntity", new object[] {
                        entityName,
                        id});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginDeleteEntity(string entityName, int id, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("DeleteEntity", new object[] {
                        entityName,
                        id}, callback, asyncState);
        }
        
        /// <remarks/>
        public int EndDeleteEntity(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.mir.co.il/DataService/GetEntityTypeClass", RequestNamespace="http://www.mir.co.il/DataService", ResponseNamespace="http://www.mir.co.il/DataService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetEntityTypeClass(string entityType) {
            object[] results = this.Invoke("GetEntityTypeClass", new object[] {
                        entityType});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetEntityTypeClass(string entityType, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetEntityTypeClass", new object[] {
                        entityType}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndGetEntityTypeClass(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.mir.co.il/DataService/LookupEntityFilter", RequestNamespace="http://www.mir.co.il/DataService", ResponseNamespace="http://www.mir.co.il/DataService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public FilterField[] LookupEntityFilter(string entityType, int entityId) {
            object[] results = this.Invoke("LookupEntityFilter", new object[] {
                        entityType,
                        entityId});
            return ((FilterField[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginLookupEntityFilter(string entityType, int entityId, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("LookupEntityFilter", new object[] {
                        entityType,
                        entityId}, callback, asyncState);
        }
        
        /// <remarks/>
        public FilterField[] EndLookupEntityFilter(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((FilterField[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.mir.co.il/DataService/GetRegion", RequestNamespace="http://www.mir.co.il/DataService", ResponseNamespace="http://www.mir.co.il/DataService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetRegion(int regionID) {
            object[] results = this.Invoke("GetRegion", new object[] {
                        regionID});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetRegion(int regionID, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetRegion", new object[] {
                        regionID}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndGetRegion(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.mir.co.il/DataService/GetRegionsData", RequestNamespace="http://www.mir.co.il/DataService", ResponseNamespace="http://www.mir.co.il/DataService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public SimpleData[] GetRegionsData() {
            object[] results = this.Invoke("GetRegionsData", new object[0]);
            return ((SimpleData[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetRegionsData(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetRegionsData", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public SimpleData[] EndGetRegionsData(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((SimpleData[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.mir.co.il/DataService/GetSportsData", RequestNamespace="http://www.mir.co.il/DataService", ResponseNamespace="http://www.mir.co.il/DataService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public SimpleData[] GetSportsData() {
            object[] results = this.Invoke("GetSportsData", new object[0]);
            return ((SimpleData[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetSportsData(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetSportsData", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public SimpleData[] EndGetSportsData(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((SimpleData[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.mir.co.il/DataService/GetChampionshipData", RequestNamespace="http://www.mir.co.il/DataService", ResponseNamespace="http://www.mir.co.il/DataService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ChampionshipData[] GetChampionshipData(int champID, int regionID) {
            object[] results = this.Invoke("GetChampionshipData", new object[] {
                        champID,
                        regionID});
            return ((ChampionshipData[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetChampionshipData(int champID, int regionID, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetChampionshipData", new object[] {
                        champID,
                        regionID}, callback, asyncState);
        }
        
        /// <remarks/>
        public ChampionshipData[] EndGetChampionshipData(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((ChampionshipData[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.mir.co.il/DataService/GetChampionshipCategories", RequestNamespace="http://www.mir.co.il/DataService", ResponseNamespace="http://www.mir.co.il/DataService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CategoryData[] GetChampionshipCategories(int champID) {
            object[] results = this.Invoke("GetChampionshipCategories", new object[] {
                        champID});
            return ((CategoryData[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetChampionshipCategories(int champID, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetChampionshipCategories", new object[] {
                        champID}, callback, asyncState);
        }
        
        /// <remarks/>
        public CategoryData[] EndGetChampionshipCategories(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((CategoryData[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.mir.co.il/DataService/GetChampionshipsData", RequestNamespace="http://www.mir.co.il/DataService", ResponseNamespace="http://www.mir.co.il/DataService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public SimpleData[] GetChampionshipsData(int region, int sport) {
            object[] results = this.Invoke("GetChampionshipsData", new object[] {
                        region,
                        sport});
            return ((SimpleData[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetChampionshipsData(int region, int sport, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetChampionshipsData", new object[] {
                        region,
                        sport}, callback, asyncState);
        }
        
        /// <remarks/>
        public SimpleData[] EndGetChampionshipsData(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((SimpleData[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.mir.co.il/DataService/GetChampionshipCategoriesBySeason", RequestNamespace="http://www.mir.co.il/DataService", ResponseNamespace="http://www.mir.co.il/DataService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int[] GetChampionshipCategoriesBySeason(int season) {
            object[] results = this.Invoke("GetChampionshipCategoriesBySeason", new object[] {
                        season});
            return ((int[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetChampionshipCategoriesBySeason(int season, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetChampionshipCategoriesBySeason", new object[] {
                        season}, callback, asyncState);
        }
        
        /// <remarks/>
        public int[] EndGetChampionshipCategoriesBySeason(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((int[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.mir.co.il/DataService/GetUserName", RequestNamespace="http://www.mir.co.il/DataService", ResponseNamespace="http://www.mir.co.il/DataService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetUserName(int userID) {
            object[] results = this.Invoke("GetUserName", new object[] {
                        userID});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetUserName(int userID, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetUserName", new object[] {
                        userID}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndGetUserName(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.mir.co.il/DataService/GetRulesetRules", RequestNamespace="http://www.mir.co.il/DataService", ResponseNamespace="http://www.mir.co.il/DataService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public RuleData[] GetRulesetRules(int rulesetID) {
            object[] results = this.Invoke("GetRulesetRules", new object[] {
                        rulesetID});
            return ((RuleData[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetRulesetRules(int rulesetID, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetRulesetRules", new object[] {
                        rulesetID}, callback, asyncState);
        }
        
        /// <remarks/>
        public RuleData[] EndGetRulesetRules(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((RuleData[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.mir.co.il/DataService/GetStudentsByName", RequestNamespace="http://www.mir.co.il/DataService", ResponseNamespace="http://www.mir.co.il/DataService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] GetStudentsByName(string firstName, string lastName) {
            object[] results = this.Invoke("GetStudentsByName", new object[] {
                        firstName,
                        lastName});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetStudentsByName(string firstName, string lastName, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetStudentsByName", new object[] {
                        firstName,
                        lastName}, callback, asyncState);
        }
        
        /// <remarks/>
        public string[] EndGetStudentsByName(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.mir.co.il/DataService/GetStudentByNumber", RequestNamespace="http://www.mir.co.il/DataService", ResponseNamespace="http://www.mir.co.il/DataService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public StudentData GetStudentByNumber(string id_number) {
            object[] results = this.Invoke("GetStudentByNumber", new object[] {
                        id_number});
            return ((StudentData)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetStudentByNumber(string id_number, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetStudentByNumber", new object[] {
                        id_number}, callback, asyncState);
        }
        
        /// <remarks/>
        public StudentData EndGetStudentByNumber(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((StudentData)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.mir.co.il/DataService/GetSchoolData", RequestNamespace="http://www.mir.co.il/DataService", ResponseNamespace="http://www.mir.co.il/DataService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public SchoolData GetSchoolData(int school_ID) {
            object[] results = this.Invoke("GetSchoolData", new object[] {
                        school_ID});
            return ((SchoolData)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetSchoolData(int school_ID, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetSchoolData", new object[] {
                        school_ID}, callback, asyncState);
        }
        
        /// <remarks/>
        public SchoolData EndGetSchoolData(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((SchoolData)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.mir.co.il/DataService/GetRegionData", RequestNamespace="http://www.mir.co.il/DataService", ResponseNamespace="http://www.mir.co.il/DataService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public RegionData GetRegionData(int region_id) {
            object[] results = this.Invoke("GetRegionData", new object[] {
                        region_id});
            return ((RegionData)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetRegionData(int region_id, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetRegionData", new object[] {
                        region_id}, callback, asyncState);
        }
        
        /// <remarks/>
        public RegionData EndGetRegionData(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((RegionData)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.mir.co.il/DataService/GetSimpleData", RequestNamespace="http://www.mir.co.il/DataService", ResponseNamespace="http://www.mir.co.il/DataService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public SimpleData GetSimpleData(int ID, string table_name, string id_field, string name_field) {
            object[] results = this.Invoke("GetSimpleData", new object[] {
                        ID,
                        table_name,
                        id_field,
                        name_field});
            return ((SimpleData)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetSimpleData(int ID, string table_name, string id_field, string name_field, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetSimpleData", new object[] {
                        ID,
                        table_name,
                        id_field,
                        name_field}, callback, asyncState);
        }
        
        /// <remarks/>
        public SimpleData EndGetSimpleData(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((SimpleData)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.mir.co.il/DataService/SetClientVersion", RequestNamespace="http://www.mir.co.il/DataService", ResponseNamespace="http://www.mir.co.il/DataService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void SetClientVersion(System.Double clientVersion) {
            this.Invoke("SetClientVersion", new object[] {
                        clientVersion});
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginSetClientVersion(System.Double clientVersion, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("SetClientVersion", new object[] {
                        clientVersion}, callback, asyncState);
        }
        
        /// <remarks/>
        public void EndSetClientVersion(System.IAsyncResult asyncResult) {
            this.EndInvoke(asyncResult);
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.mir.co.il/DataService/GetLatestSeason", RequestNamespace="http://www.mir.co.il/DataService", ResponseNamespace="http://www.mir.co.il/DataService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int GetLatestSeason() {
            object[] results = this.Invoke("GetLatestSeason", new object[0]);
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetLatestSeason(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetLatestSeason", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public int EndGetLatestSeason(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((int)(results[0]));
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.mir.co.il/DataService")]
    public class FilterField {
        
        /// <remarks/>
        public int Field;
        
        /// <remarks/>
        public object Value;
        
        /// <remarks/>
        public bool Not;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.mir.co.il/DataService")]
    public class RuleData {
        
        /// <remarks/>
        public int RuleID;
        
        /// <remarks/>
        public RuleSetData Ruleset;
        
        /// <remarks/>
        public SimpleData RuleType;
        
        /// <remarks/>
        public string Value;
        
        /// <remarks/>
        public SportFieldTypeData SportFieldType;
        
        /// <remarks/>
        public SportFieldData SportField;
        
        /// <remarks/>
        public int Category;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.mir.co.il/DataService")]
    public class RuleSetData {
        
        /// <remarks/>
        public int ID;
        
        /// <remarks/>
        public string Name;
        
        /// <remarks/>
        public SportData Sport;
        
        /// <remarks/>
        public RegionData Region;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.mir.co.il/DataService")]
    public class SportData {
        
        /// <remarks/>
        public int ID;
        
        /// <remarks/>
        public string Name;
        
        /// <remarks/>
        public int Type;
        
        /// <remarks/>
        public RuleSetData Ruleset;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.mir.co.il/DataService")]
    public class RegionData {
        
        /// <remarks/>
        public int ID;
        
        /// <remarks/>
        public string Name;
        
        /// <remarks/>
        public string Address;
        
        /// <remarks/>
        public string Phone;
        
        /// <remarks/>
        public string Fax;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.mir.co.il/DataService")]
    public class SimpleData {
        
        /// <remarks/>
        public int ID;
        
        /// <remarks/>
        public string Name;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.mir.co.il/DataService")]
    public class SportFieldTypeData {
        
        /// <remarks/>
        public int ID;
        
        /// <remarks/>
        public string Name;
        
        /// <remarks/>
        public SportData Sport;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.mir.co.il/DataService")]
    public class SportFieldData {
        
        /// <remarks/>
        public int ID;
        
        /// <remarks/>
        public string Name;
        
        /// <remarks/>
        public SportFieldTypeData SportFieldType;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.mir.co.il/DataService")]
    public class Entity {
        
        /// <remarks/>
        public object[] Fields;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.mir.co.il/DataService")]
    public class StudentData {
        
        /// <remarks/>
        public int ID;
        
        /// <remarks/>
        public string Name;
        
        /// <remarks/>
        public string IdNumber;
        
        /// <remarks/>
        public string FirstName;
        
        /// <remarks/>
        public string LastName;
        
        /// <remarks/>
        public System.DateTime Birthdate;
        
        /// <remarks/>
        public SchoolData School;
        
        /// <remarks/>
        public int Grade;
        
        /// <remarks/>
        public int SexType;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.mir.co.il/DataService")]
    public class SchoolData {
        
        /// <remarks/>
        public int ID;
        
        /// <remarks/>
        public string Name;
        
        /// <remarks/>
        public string Symbol;
        
        /// <remarks/>
        public string City;
        
        /// <remarks/>
        public int FromGrade;
        
        /// <remarks/>
        public int ToGrade;
        
        /// <remarks/>
        public RegionData Region;
        
        /// <remarks/>
        public bool IsClub;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.mir.co.il/DataService")]
    public class PlayerData {
        
        /// <remarks/>
        public int ID;
        
        /// <remarks/>
        public StudentData Student;
        
        /// <remarks/>
        public TeamData Team;
        
        /// <remarks/>
        public int ShirtNumber;
        
        /// <remarks/>
        public int ChipNumber;
        
        /// <remarks/>
        public int Status;
        
        /// <remarks/>
        public string Remarks;
        
        /// <remarks/>
        public System.DateTime RegistrationDate;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.mir.co.il/DataService")]
    public class TeamData {
        
        /// <remarks/>
        public int ID;
        
        /// <remarks/>
        public SchoolData School;
        
        /// <remarks/>
        public ChampionshipData Championship;
        
        /// <remarks/>
        public CategoryData ChampionshipCategory;
        
        /// <remarks/>
        public int Status;
        
        /// <remarks/>
        public int TeamIndex;
        
        /// <remarks/>
        public string Supervisor;
        
        /// <remarks/>
        public System.DateTime RegistrationDate;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.mir.co.il/DataService")]
    public class ChampionshipData {
        
        /// <remarks/>
        public int ID;
        
        /// <remarks/>
        public int Season;
        
        /// <remarks/>
        public string Name;
        
        /// <remarks/>
        public RegionData Region;
        
        /// <remarks/>
        public SportData Sport;
        
        /// <remarks/>
        public bool IsClubs;
        
        /// <remarks/>
        public System.DateTime LastRegistrationDate;
        
        /// <remarks/>
        public System.DateTime StartDate;
        
        /// <remarks/>
        public System.DateTime EndDate;
        
        /// <remarks/>
        public System.DateTime AltStartDate;
        
        /// <remarks/>
        public System.DateTime AltEndDate;
        
        /// <remarks/>
        public System.DateTime FinalsDate;
        
        /// <remarks/>
        public System.DateTime AltFinalsDate;
        
        /// <remarks/>
        public RuleSetData RuleSet;
        
        /// <remarks/>
        public bool IsOpen;
        
        /// <remarks/>
        public int Status;
        
        /// <remarks/>
        public string Supervisor;
        
        /// <remarks/>
        public SimpleData StandardChampionship;
        
        /// <remarks/>
        public CategoryData[] Categories;
        
        /// <remarks/>
        public string GameStructureRule;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.mir.co.il/DataService")]
    public class CategoryData {
        
        /// <remarks/>
        public int ID;
        
        /// <remarks/>
        public int Championship;
        
        /// <remarks/>
        public int Category;
        
        /// <remarks/>
        public PhaseData[] Phases;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.mir.co.il/DataService")]
    public class PhaseData {
        
        /// <remarks/>
        public int CategoryID;
        
        /// <remarks/>
        public int PhaseIndex;
        
        /// <remarks/>
        public string PhaseName;
        
        /// <remarks/>
        public int Status;
        
        /// <remarks/>
        public GroupData[] Groups;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.mir.co.il/DataService")]
    public class GroupData {
        
        /// <remarks/>
        public PhaseData Phase;
        
        /// <remarks/>
        public int GroupIndex;
        
        /// <remarks/>
        public string GroupName;
        
        /// <remarks/>
        public int Status;
        
        /// <remarks/>
        public RoundData[] Rounds;
        
        /// <remarks/>
        public CompetitionData[] Competitions;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.mir.co.il/DataService")]
    public class RoundData {
        
        /// <remarks/>
        public GroupData Group;
        
        /// <remarks/>
        public int RoundIndex;
        
        /// <remarks/>
        public string RoundName;
        
        /// <remarks/>
        public int Status;
        
        /// <remarks/>
        public MatchData[] Matches;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.mir.co.il/DataService")]
    public class MatchData {
        
        /// <remarks/>
        public RoundData Round;
        
        /// <remarks/>
        public int Cycle;
        
        /// <remarks/>
        public int MatchIndex;
        
        /// <remarks/>
        public TeamData TeamA;
        
        /// <remarks/>
        public TeamData TeamB;
        
        /// <remarks/>
        public System.DateTime Time;
        
        /// <remarks/>
        public FacilityData Facility;
        
        /// <remarks/>
        public CourtData Court;
        
        /// <remarks/>
        public System.Double TeamA_Score;
        
        /// <remarks/>
        public System.Double TeamB_Score;
        
        /// <remarks/>
        public int Result;
        
        /// <remarks/>
        public string PartsResult;
        
        /// <remarks/>
        public int CategoryID;
        
        /// <remarks/>
        public int PhaseIndex;
        
        /// <remarks/>
        public int GroupIndex;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.mir.co.il/DataService")]
    public class FacilityData {
        
        /// <remarks/>
        public int ID;
        
        /// <remarks/>
        public string Name;
        
        /// <remarks/>
        public RegionData Region;
        
        /// <remarks/>
        public SchoolData School;
        
        /// <remarks/>
        public string Address;
        
        /// <remarks/>
        public string Phone;
        
        /// <remarks/>
        public string Fax;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.mir.co.il/DataService")]
    public class CourtData {
        
        /// <remarks/>
        public int ID;
        
        /// <remarks/>
        public string Name;
        
        /// <remarks/>
        public FacilityData Facility;
        
        /// <remarks/>
        public SimpleData CourtType;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.mir.co.il/DataService")]
    public class CompetitionData {
        
        /// <remarks/>
        public GroupData Group;
        
        /// <remarks/>
        public int CompetitionIndex;
        
        /// <remarks/>
        public SportFieldData SportField;
        
        /// <remarks/>
        public System.DateTime Time;
        
        /// <remarks/>
        public FacilityData Facility;
        
        /// <remarks/>
        public CourtData Court;
        
        /// <remarks/>
        public HeatData[] Heats;
        
        /// <remarks/>
        public CompetitorData[] Competitors;
        
        /// <remarks/>
        public int CategoryID;
        
        /// <remarks/>
        public int PhaseIndex;
        
        /// <remarks/>
        public int GroupIndex;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.mir.co.il/DataService")]
    public class HeatData {
        
        /// <remarks/>
        public CompetitionData Competition;
        
        /// <remarks/>
        public int HeatIndex;
        
        /// <remarks/>
        public System.DateTime Time;
        
        /// <remarks/>
        public FacilityData Facility;
        
        /// <remarks/>
        public CourtData Court;
        
        /// <remarks/>
        public int CategoryID;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.mir.co.il/DataService")]
    public class CompetitorData {
        
        /// <remarks/>
        public CompetitionData Competition;
        
        /// <remarks/>
        public int CompetitorIndex;
        
        /// <remarks/>
        public PlayerData Player;
        
        /// <remarks/>
        public HeatData Heat;
        
        /// <remarks/>
        public int Position;
        
        /// <remarks/>
        public int ResultPosition;
        
        /// <remarks/>
        public string Result;
        
        /// <remarks/>
        public int Score;
        
        /// <remarks/>
        public string Rule;
        
        /// <remarks/>
        public string MeasureType;
    }
}
