//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace Sport.Rulesets.SportServices {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="RulesetServiceSoap", Namespace="http://www.mir.co.il/")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(object[]))]
    public partial class RulesetService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetScoreTablesByFormatOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetPointsNameOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetRuleTypesOperationCompleted;
        
        private System.Threading.SendOrPostCallback LoadRulesetOperationCompleted;
        
        private System.Threading.SendOrPostCallback SaveRulesetOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public RulesetService() {
            this.Url = global::Sport.Rulesets.Properties.Settings.Default.Sport_Rulesets_SportServices_RulesetService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetScoreTablesByFormatCompletedEventHandler GetScoreTablesByFormatCompleted;
        
        /// <remarks/>
        public event GetPointsNameCompletedEventHandler GetPointsNameCompleted;
        
        /// <remarks/>
        public event GetRuleTypesCompletedEventHandler GetRuleTypesCompleted;
        
        /// <remarks/>
        public event LoadRulesetCompletedEventHandler LoadRulesetCompleted;
        
        /// <remarks/>
        public event SaveRulesetCompletedEventHandler SaveRulesetCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.mir.co.il/GetScoreTablesByFormat", RequestNamespace="http://www.mir.co.il/", ResponseNamespace="http://www.mir.co.il/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public object[] GetScoreTablesByFormat(string format) {
            object[] results = this.Invoke("GetScoreTablesByFormat", new object[] {
                        format});
            return ((object[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetScoreTablesByFormat(string format, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetScoreTablesByFormat", new object[] {
                        format}, callback, asyncState);
        }
        
        /// <remarks/>
        public object[] EndGetScoreTablesByFormat(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((object[])(results[0]));
        }
        
        /// <remarks/>
        public void GetScoreTablesByFormatAsync(string format) {
            this.GetScoreTablesByFormatAsync(format, null);
        }
        
        /// <remarks/>
        public void GetScoreTablesByFormatAsync(string format, object userState) {
            if ((this.GetScoreTablesByFormatOperationCompleted == null)) {
                this.GetScoreTablesByFormatOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetScoreTablesByFormatOperationCompleted);
            }
            this.InvokeAsync("GetScoreTablesByFormat", new object[] {
                        format}, this.GetScoreTablesByFormatOperationCompleted, userState);
        }
        
        private void OnGetScoreTablesByFormatOperationCompleted(object arg) {
            if ((this.GetScoreTablesByFormatCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetScoreTablesByFormatCompleted(this, new GetScoreTablesByFormatCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.mir.co.il/GetPointsName", RequestNamespace="http://www.mir.co.il/", ResponseNamespace="http://www.mir.co.il/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetPointsName(int sportID) {
            object[] results = this.Invoke("GetPointsName", new object[] {
                        sportID});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetPointsName(int sportID, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetPointsName", new object[] {
                        sportID}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndGetPointsName(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetPointsNameAsync(int sportID) {
            this.GetPointsNameAsync(sportID, null);
        }
        
        /// <remarks/>
        public void GetPointsNameAsync(int sportID, object userState) {
            if ((this.GetPointsNameOperationCompleted == null)) {
                this.GetPointsNameOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetPointsNameOperationCompleted);
            }
            this.InvokeAsync("GetPointsName", new object[] {
                        sportID}, this.GetPointsNameOperationCompleted, userState);
        }
        
        private void OnGetPointsNameOperationCompleted(object arg) {
            if ((this.GetPointsNameCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetPointsNameCompleted(this, new GetPointsNameCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.mir.co.il/GetRuleTypes", RequestNamespace="http://www.mir.co.il/", ResponseNamespace="http://www.mir.co.il/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public RuleType[] GetRuleTypes() {
            object[] results = this.Invoke("GetRuleTypes", new object[0]);
            return ((RuleType[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetRuleTypes(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetRuleTypes", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public RuleType[] EndGetRuleTypes(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((RuleType[])(results[0]));
        }
        
        /// <remarks/>
        public void GetRuleTypesAsync() {
            this.GetRuleTypesAsync(null);
        }
        
        /// <remarks/>
        public void GetRuleTypesAsync(object userState) {
            if ((this.GetRuleTypesOperationCompleted == null)) {
                this.GetRuleTypesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetRuleTypesOperationCompleted);
            }
            this.InvokeAsync("GetRuleTypes", new object[0], this.GetRuleTypesOperationCompleted, userState);
        }
        
        private void OnGetRuleTypesOperationCompleted(object arg) {
            if ((this.GetRuleTypesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetRuleTypesCompleted(this, new GetRuleTypesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.mir.co.il/LoadRuleset", RequestNamespace="http://www.mir.co.il/", ResponseNamespace="http://www.mir.co.il/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Ruleset LoadRuleset(int rulesetId) {
            object[] results = this.Invoke("LoadRuleset", new object[] {
                        rulesetId});
            return ((Ruleset)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginLoadRuleset(int rulesetId, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("LoadRuleset", new object[] {
                        rulesetId}, callback, asyncState);
        }
        
        /// <remarks/>
        public Ruleset EndLoadRuleset(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((Ruleset)(results[0]));
        }
        
        /// <remarks/>
        public void LoadRulesetAsync(int rulesetId) {
            this.LoadRulesetAsync(rulesetId, null);
        }
        
        /// <remarks/>
        public void LoadRulesetAsync(int rulesetId, object userState) {
            if ((this.LoadRulesetOperationCompleted == null)) {
                this.LoadRulesetOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLoadRulesetOperationCompleted);
            }
            this.InvokeAsync("LoadRuleset", new object[] {
                        rulesetId}, this.LoadRulesetOperationCompleted, userState);
        }
        
        private void OnLoadRulesetOperationCompleted(object arg) {
            if ((this.LoadRulesetCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LoadRulesetCompleted(this, new LoadRulesetCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.mir.co.il/SaveRuleset", RequestNamespace="http://www.mir.co.il/", ResponseNamespace="http://www.mir.co.il/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool SaveRuleset(Ruleset ruleset) {
            object[] results = this.Invoke("SaveRuleset", new object[] {
                        ruleset});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginSaveRuleset(Ruleset ruleset, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("SaveRuleset", new object[] {
                        ruleset}, callback, asyncState);
        }
        
        /// <remarks/>
        public bool EndSaveRuleset(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void SaveRulesetAsync(Ruleset ruleset) {
            this.SaveRulesetAsync(ruleset, null);
        }
        
        /// <remarks/>
        public void SaveRulesetAsync(Ruleset ruleset, object userState) {
            if ((this.SaveRulesetOperationCompleted == null)) {
                this.SaveRulesetOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSaveRulesetOperationCompleted);
            }
            this.InvokeAsync("SaveRuleset", new object[] {
                        ruleset}, this.SaveRulesetOperationCompleted, userState);
        }
        
        private void OnSaveRulesetOperationCompleted(object arg) {
            if ((this.SaveRulesetCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SaveRulesetCompleted(this, new SaveRulesetCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.mir.co.il/")]
    public partial class Rule {
        
        private int idField;
        
        private int ruleTypeField;
        
        private string valueField;
        
        private int sportFieldTypeField;
        
        private int sportFieldField;
        
        private int categoryField;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public int RuleType {
            get {
                return this.ruleTypeField;
            }
            set {
                this.ruleTypeField = value;
            }
        }
        
        /// <remarks/>
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
        
        /// <remarks/>
        public int SportFieldType {
            get {
                return this.sportFieldTypeField;
            }
            set {
                this.sportFieldTypeField = value;
            }
        }
        
        /// <remarks/>
        public int SportField {
            get {
                return this.sportFieldField;
            }
            set {
                this.sportFieldField = value;
            }
        }
        
        /// <remarks/>
        public int Category {
            get {
                return this.categoryField;
            }
            set {
                this.categoryField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.mir.co.il/")]
    public partial class Ruleset {
        
        private int idField;
        
        private string nameField;
        
        private int sportField;
        
        private int sportTypeField;
        
        private int sportRulesetField;
        
        private Rule[] rulesField;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public int Sport {
            get {
                return this.sportField;
            }
            set {
                this.sportField = value;
            }
        }
        
        /// <remarks/>
        public int SportType {
            get {
                return this.sportTypeField;
            }
            set {
                this.sportTypeField = value;
            }
        }
        
        /// <remarks/>
        public int SportRuleset {
            get {
                return this.sportRulesetField;
            }
            set {
                this.sportRulesetField = value;
            }
        }
        
        /// <remarks/>
        public Rule[] Rules {
            get {
                return this.rulesField;
            }
            set {
                this.rulesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.mir.co.il/")]
    public partial class RuleType {
        
        private int idField;
        
        private string classField;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Class {
            get {
                return this.classField;
            }
            set {
                this.classField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void GetScoreTablesByFormatCompletedEventHandler(object sender, GetScoreTablesByFormatCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetScoreTablesByFormatCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetScoreTablesByFormatCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public object[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((object[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void GetPointsNameCompletedEventHandler(object sender, GetPointsNameCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetPointsNameCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetPointsNameCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void GetRuleTypesCompletedEventHandler(object sender, GetRuleTypesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetRuleTypesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetRuleTypesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public RuleType[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((RuleType[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void LoadRulesetCompletedEventHandler(object sender, LoadRulesetCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LoadRulesetCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LoadRulesetCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Ruleset Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Ruleset)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void SaveRulesetCompletedEventHandler(object sender, SaveRulesetCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SaveRulesetCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SaveRulesetCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591