-- =============================================
-- SportTables.sql
--		Creating sport tables:
--			SPORTS
--			SPORT_FIELD_TYPES
--			SPORT_FIELDS
-- =============================================

-- Deleting existing tables
-- ============================================
IF EXISTS(SELECT * FROM sysobjects WHERE name = 'SPORT_FIELDS' AND type = 'U')
	DROP TABLE SPORT_FIELDS
GO
IF EXISTS(SELECT * FROM sysobjects WHERE name = 'SPORT_FIELD_TYPES' AND type = 'U')
	DROP TABLE SPORT_FIELD_TYPES
GO
IF EXISTS(SELECT * FROM sysobjects WHERE name = 'SPORTS' AND type = 'U')
	DROP TABLE SPORTS
GO

-- =======    SPORTS TABLE   ======
CREATE TABLE SPORTS (
SPORT_ID			int				IDENTITY (1,1),
SPORT_NAME			nvarchar(50),
SPORT_TYPE			int				NOT NULL, -- 1 Competition 2 Match
POINTS_NAME			nvarchar(20),
DATE_LAST_MODIFIED	DATETIME,
DATE_DELETED datetime,
timestamp
CONSTRAINT PK_SPORTS PRIMARY KEY(SPORT_ID),
CONSTRAINT CHK_SPORT_TYPE CHECK (SPORT_TYPE IN (1, 2))
)
GO

-- =======    SPORT_FIELD_TYPES TABLE   ======
CREATE TABLE SPORT_FIELD_TYPES (
SPORT_FIELD_TYPE_ID		int		IDENTITY (1,1),
SPORT_ID				int,
SPORT_FIELD_TYPE_NAME	nvarchar(50),
COMPETITION_TYPE		int NOT NULL, -- 0 personal, 1 group
DATE_LAST_MODIFIED DATETIME,
DATE_DELETED datetime,
timestamp,
CONSTRAINT PK_SPORT_FIELD_TYPES PRIMARY KEY(SPORT_FIELD_TYPE_ID),
CONSTRAINT FK_SPORTFIELDTYPE_SPORT FOREIGN KEY(SPORT_ID)
	REFERENCES SPORTS(SPORT_ID)
)
GO

-- =======    SPORT_FIELDS TABLE   ======
CREATE TABLE SPORT_FIELDS (
SPORT_FIELD_ID		int		IDENTITY (1,1),
SPORT_FIELD_TYPE_ID int,
SPORT_FIELD_NAME	nvarchar(50),
DATE_LAST_MODIFIED DATETIME,
DATE_DELETED datetime,
timestamp,
CONSTRAINT PK_SPORT_FIELDS PRIMARY KEY(SPORT_FIELD_ID),
CONSTRAINT FK_SPORTFIELD_FIELDTYPE FOREIGN KEY(SPORT_FIELD_TYPE_ID)
	REFERENCES SPORT_FIELD_TYPES(SPORT_FIELD_TYPE_ID),
CONSTRAINT UN_SPORTFIELD_TYPEFIELD UNIQUE(SPORT_FIELD_TYPE_ID, SPORT_FIELD_ID, DATE_DELETED)
)
GO