//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportSite.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://213.8.193.150/ISF/SportServices/PlayerCardService.asmx")]
        public string SportSite_PlayerCardService_PlayerCardService {
            get {
                return ((string)(this["SportSite_PlayerCardService_PlayerCardService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://213.8.193.150/ISF/SportServices/SessionService.asmx")]
        public string SportSite_SessionService_SessionService {
            get {
                return ((string)(this["SportSite_SessionService_SessionService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://213.8.193.150/ISF/SportServices/AdvancedService.asmx")]
        public string SportSite_AdvancedServices_AdvancedService {
            get {
                return ((string)(this["SportSite_AdvancedServices_AdvancedService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://213.8.193.150/ISF/SportServices/ChampionshipService.asmx")]
        public string SportSite_ChampionshipServices_ChampionshipService {
            get {
                return ((string)(this["SportSite_ChampionshipServices_ChampionshipService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://213.8.193.150/ISF/SportServices/PermissionService.asmx")]
        public string SportSite_PermissionServices_PermissionService {
            get {
                return ((string)(this["SportSite_PermissionServices_PermissionService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://213.8.193.150/ISF/SportServices/PlayerCardService.asmx")]
        public string SportSite_PlayerCardServices_PlayerCardService {
            get {
                return ((string)(this["SportSite_PlayerCardServices_PlayerCardService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://213.8.193.150/ISF/SportServices/SessionService.asmx")]
        public string SportSite_SessionServices_SessionService {
            get {
                return ((string)(this["SportSite_SessionServices_SessionService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://213.8.193.150/ISF/SportServices/WebsiteService.asmx")]
        public string SportSite_WebSiteServices_WebsiteService {
            get {
                return ((string)(this["SportSite_WebSiteServices_WebsiteService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://213.8.193.150/ISF/SportServices/DataService.asmx")]
        public string Sport_Championships_DataServices_DataService {
            get {
                return ((string)(this["Sport_Championships_DataServices_DataService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://213.8.193.150/ISF/SportServices/ChampionshipService.asmx")]
        public string Sport_Championships_SportServices_ChampionshipService {
            get {
                return ((string)(this["Sport_Championships_SportServices_ChampionshipService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://213.8.193.150/ISF/SportServices/DataService.asmx")]
        public string SportSite_DataServices1_DataService {
            get {
                return ((string)(this["SportSite_DataServices1_DataService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://213.8.193.150/ISF/SportServices/RegistrationService.asmx")]
        public string SportSite_RegistrationService_RegistrationService {
            get {
                return ((string)(this["SportSite_RegistrationService_RegistrationService"]));
            }
        }
    }
}
